/* DAMRU TRUTH FORGE — answer self-audit, adversarial challenge, repair, Proof Passport */
(function(){
'use strict'; if(window.DamruTruthForge)return;
var current=null, lastAudit=null, busy=false;
function E(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function chakra(n,c){return window.DamruChakra&&DamruChakra.svg?DamruChakra.svg(n,c||'pulse'):'⚖';}
function injectCSS(){if(document.getElementById('tf-css'))return;var x=document.createElement('style');x.id='tf-css';x.textContent=`
#tf-modal{position:fixed;inset:0;z-index:2147482000;background:rgba(2,5,13,.78);backdrop-filter:blur(14px);display:none;align-items:center;justify-content:center;padding:18px;color:#edf3ff}#tf-modal.on{display:flex}
.tf-shell{width:min(1040px,100%);height:min(820px,94dvh);background:linear-gradient(145deg,#10182c,#080d19 70%);border:1px solid rgba(83,133,255,.36);border-radius:22px;box-shadow:0 28px 90px rgba(0,0,0,.68);display:flex;flex-direction:column;overflow:hidden}.tf-head{display:flex;align-items:center;gap:12px;padding:15px 18px;border-bottom:1px solid rgba(255,255,255,.09);background:rgba(13,25,54,.68)}.tf-title{font:700 1.05rem/1.2 Inter,sans-serif}.tf-sub{font-size:.68rem;color:#8da9e8;margin-top:3px}.tf-x{margin-left:auto;width:34px;height:34px;border:1px solid rgba(255,255,255,.12);border-radius:10px;background:transparent;color:#dce7ff;font-size:20px;cursor:pointer}.tf-body{padding:16px;overflow:auto;flex:1}.tf-warning{padding:10px 12px;border:1px solid rgba(255,190,80,.25);background:rgba(255,176,47,.08);border-radius:12px;color:#d9c08a;font-size:.74rem;line-height:1.5}.tf-grid{display:grid;grid-template-columns:220px 1fr;gap:14px;margin-top:14px}.tf-score{border:1px solid rgba(84,135,255,.25);border-radius:16px;padding:16px;background:rgba(31,59,122,.15);text-align:center}.tf-num{font-size:2.7rem;font-weight:800;color:#79a2ff}.tf-label{font-size:.65rem;color:#91a5d0;letter-spacing:.1em}.tf-metrics{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:14px}.tf-metric{padding:9px;border-radius:10px;background:rgba(255,255,255,.045);font-size:.7rem;color:#9eb2dc}.tf-metric b{display:block;color:#fff;font-size:1rem}.tf-panel{border:1px solid rgba(255,255,255,.09);border-radius:16px;padding:14px;background:rgba(255,255,255,.025)}.tf-panel h3{font-size:.83rem;margin:0 0 10px}.tf-claim{padding:10px;border-left:3px solid #638eff;background:rgba(92,137,255,.07);border-radius:7px;margin:8px 0;font-size:.75rem;line-height:1.45}.tf-claim.needs_evidence,.tf-claim.uncertain{border-color:#e0ad53}.tf-claim.contradicted{border-color:#e05d67}.tf-status{font-size:.58rem;text-transform:uppercase;letter-spacing:.08em;color:#8eacf0}.tf-actions{display:flex;gap:8px;flex-wrap:wrap;padding:13px 16px;border-top:1px solid rgba(255,255,255,.08)}.tf-btn{border:1px solid rgba(94,142,255,.32);background:rgba(52,89,174,.16);color:#dfe8ff;padding:9px 13px;border-radius:11px;font-weight:650;font-size:.74rem;cursor:pointer}.tf-btn.primary{background:linear-gradient(135deg,#315fcb,#5788f4);color:white}.tf-btn:disabled{opacity:.45}.tf-empty{color:#8fa1c4;padding:18px;text-align:center}.tf-proof-act{width:auto!important;padding:0 8px!important;font-size:.68rem!important;color:#8fb0ff!important;border-color:rgba(79,134,255,.2)!important}.tf-nav{position:relative}.tf-new{margin-left:auto;font-size:.52rem;padding:2px 5px;border-radius:8px;background:#315fc4;color:white}.tf-loading{display:flex;align-items:center;gap:10px;padding:18px;color:#9eb8f2}.tf-json{font:11px/1.5 ui-monospace,monospace;white-space:pre-wrap;color:#9db2df}.tf-answer{max-height:150px;overflow:auto;font-size:.7rem;color:#aebddd;border-left:2px solid #365fb8;padding-left:10px;margin-top:10px}
@media(max-width:720px){.tf-grid{grid-template-columns:1fr}.tf-shell{height:96dvh;border-radius:16px}.tf-metrics{grid-template-columns:repeat(4,1fr)}.tf-metric{padding:7px;font-size:.58rem}.tf-metric b{font-size:.82rem}}
`;document.head.appendChild(x);}
function modal(){var m=document.getElementById('tf-modal');if(m)return m;m=document.createElement('div');m.id='tf-modal';m.innerHTML=`<div class="tf-shell"><div class="tf-head">${chakra(30,'pulse')}<div><div class="tf-title">Damru Truth Forge</div><div class="tf-sub">Claim ledger · adversarial audit · repair · Proof Passport</div></div><button class="tf-x" aria-label="Close">×</button></div><div class="tf-body" id="tf-body"></div><div class="tf-actions"><button class="tf-btn primary" id="tf-deep">⚡ Deep Audit</button><button class="tf-btn" id="tf-challenge">🥊 Challenge</button><button class="tf-btn" id="tf-repair">🛠 Repair Answer</button><button class="tf-btn" id="tf-export">⬇ Proof Passport</button></div></div>`;document.body.appendChild(m);m.querySelector('.tf-x').onclick=close;m.onclick=function(e){if(e.target===m)close();};document.getElementById('tf-deep').onclick=function(){deep(false);};document.getElementById('tf-challenge').onclick=function(){deep(true);};document.getElementById('tf-repair').onclick=repair;document.getElementById('tf-export').onclick=exportPassport;return m;}
function localAudit(q,a){var links=(a.match(/https?:\/\/\S+/g)||[]).length,code=(a.match(/```/g)||[]).length/2,numbers=(a.match(/\b\d+(?:\.\d+)?%?\b/g)||[]).length,claims=a.split(/[.!?]\n?/) .filter(function(x){return x.trim().length>35;}).length,caveats=(a.match(/uncertain|may|might|estimate|approximately|verify|check|depends|संभव|जाँच|लगभग/gi)||[]).length;var fresh=/today|latest|current|news|price|202[5-9]|आज|ताज़ा/i.test(q);var score=28+Math.min(22,links*7)+Math.min(18,caveats*4)+Math.min(16,code*5)+Math.min(10,claims?6:0)-(fresh&&!links?18:0);score=Math.max(5,Math.min(92,Math.round(score)));return {kind:'local-readiness-not-truth',readiness_score:score,metrics:{claims:claims,links:links,code_blocks:code,numeric_claims:numbers},freshness_risk:fresh&&!links,summary:fresh&&!links?'Fresh/current request has no visible source links. Deep verification recommended.':'Answer is ready for a claim-level audit; this local score does not establish factual truth.',claims:[],unknowns:[],recommended_checks:[]};}
async function digest(q,a){try{var b=new TextEncoder().encode(q+'\n---\n'+a),h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(function(x){return x.toString(16).padStart(2,'0');}).join('');}catch(e){return 'sha256-unavailable';}}
function render(a){lastAudit=a;var m=a.metrics||{},claims=a.claims||[],unknown=a.unknowns||[],checks=a.recommended_checks||[];document.getElementById('tf-body').innerHTML=`<div class="tf-warning"><b>Honest mode:</b> “Verification readiness” is not an accuracy percentage. Deep Audit is a second model pass, not independent ground truth. Important claims still require sources, execution or expert review.</div><div class="tf-grid"><div class="tf-score"><div class="tf-num">${E(a.readiness_score==null?'—':a.readiness_score)}</div><div class="tf-label">VERIFICATION READINESS</div><div class="tf-metrics"><div class="tf-metric"><b>${E(m.claims||claims.length||0)}</b>claims</div><div class="tf-metric"><b>${E(m.links||0)}</b>links</div><div class="tf-metric"><b>${E(m.code_blocks||0)}</b>code</div><div class="tf-metric"><b>${E(m.numeric_claims||0)}</b>numbers</div></div></div><div class="tf-panel"><h3>Audit summary</h3><div>${E(a.summary||'Audit ready.')}</div>${claims.length?claims.map(function(c){return `<div class="tf-claim ${E(c.status||'uncertain')}"><div class="tf-status">${E(c.status||'uncertain')} · risk ${E(c.risk||'unknown')}</div><b>${E(c.claim||'')}</b><br>${E(c.evidence_needed||c.reason||'')}</div>`;}).join(''):'<div class="tf-empty">Run Deep Audit for a claim-by-claim ledger.</div>'}${unknown.length?'<h3>Unknowns</h3><ul>'+unknown.map(function(x){return '<li>'+E(x)+'</li>';}).join('')+'</ul>':''}${checks.length?'<h3>Recommended checks</h3><ul>'+checks.map(function(x){return '<li>'+E(x)+'</li>';}).join('')+'</ul>':''}<div class="tf-answer"><b>Answer under audit:</b><br>${E(current.answer.slice(0,1200))}</div></div></div>`;}
function open(q,a){current={question:String(q||''),answer:String(a||'')};lastAudit=localAudit(current.question,current.answer);modal().classList.add('on');render(lastAudit);}
function close(){var m=document.getElementById('tf-modal');if(m)m.classList.remove('on');if(window.DamruChakra)DamruChakra.setState('ready','READY');}
function parseJSON(t){var x=String(t||''),f=x.match(/```(?:json)?\s*([\s\S]*?)```/i);if(f)x=f[1];var a=x.indexOf('{'),b=x.lastIndexOf('}');if(a<0||b<a)throw Error('Audit returned no JSON');return JSON.parse(x.slice(a,b+1).replace(/,\s*([}\]])/g,'$1'));}
async function deep(adversarial){if(!current||busy)return;busy=true;setButtons(true);if(window.DamruChakra)DamruChakra.setState('verify',adversarial?'CHALLENGE':'AUDIT');document.getElementById('tf-body').innerHTML='<div class="tf-loading">'+chakra(34,'spin')+' '+(adversarial?'Red-team attacking strongest claims…':'Building claim ledger without inventing evidence…')+'</div>';try{if(typeof engine!=='function')throw Error('Damru engine unavailable');var sys=`You are DAMRU TRUTH FORGE, an honest answer auditor. Return ONLY strict JSON. Never invent a citation, source, execution result or certainty. A second model pass is not independent proof. Schema: {"readiness_score":0-100,"summary":string,"metrics":{"claims":number,"links":number,"code_blocks":number,"numeric_claims":number},"claims":[{"claim":string,"status":"supported|needs_evidence|uncertain|contradicted","risk":"low|medium|high","evidence_needed":string}],"unknowns":[string],"recommended_checks":[string]}. ${adversarial?'Act as an adversarial red team: seek counterexamples, stale facts, hidden assumptions and unsafe code paths.':'Extract the most consequential claims and identify what evidence or execution would verify each.'}`;var out=await engine([{role:'system',content:sys},{role:'user',content:'QUESTION:\n'+current.question+'\n\nANSWER:\n'+current.answer}],2400,.08,'research');var a=parseJSON(out);a.kind=adversarial?'adversarial-model-audit':'model-self-audit';render(a);}catch(e){render(Object.assign(localAudit(current.question,current.answer),{summary:'Deep audit unavailable: '+String(e.message||e)}));}finally{busy=false;setButtons(false);if(window.DamruChakra)DamruChakra.setState('ready','READY');}}
async function repair(){if(!current||busy)return;busy=true;setButtons(true);if(window.DamruChakra)DamruChakra.setState('building','REPAIR');try{if(typeof engine!=='function')throw Error('Damru engine unavailable');var audit=JSON.stringify(lastAudit||localAudit(current.question,current.answer));var sys='You are Damru Repair Forge. Rewrite the answer to be materially stronger after the audit. Correct errors, remove unsupported certainty, clearly label unknowns, add verification steps, and preserve useful detail. Never claim a source or test you did not actually use. Return the repaired answer only.';var ans=await engine([{role:'system',content:sys},{role:'user',content:'QUESTION:\n'+current.question+'\n\nOLD ANSWER:\n'+current.answer+'\n\nAUDIT:\n'+audit}],3200,.18,'research');close();if(typeof typeAssistantAnswer==='function')await typeAssistantAnswer(ans,current.question,'truth-repair','');else if(typeof addMsg==='function')addMsg('ai',renderMD(ans),ans,current.question,'truth-repair');if(typeof history!=='undefined'){history.push({role:'assistant',content:ans,q:current.question,intent:'truth-repair'});if(typeof saveCur==='function')saveCur();}if(typeof toast==='function')toast('Truth Forge repaired the answer');}catch(e){if(typeof toast==='function')toast('Repair failed: '+String(e.message||e));}finally{busy=false;setButtons(false);if(window.DamruChakra)DamruChakra.setState('ready','READY');}}
async function exportPassport(){if(!current)return;var pass={format:'DAMRU_PROOF_PASSPORT_V1',created_at:new Date().toISOString(),question:current.question,answer:current.answer,audit:lastAudit||localAudit(current.question,current.answer),disclaimer:'Self-audit is not independent ground truth.'};pass.sha256=await digest(current.question,current.answer);var blob=new Blob([JSON.stringify(pass,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='damru-proof-'+pass.sha256.slice(0,12)+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(u);},500);}
function setButtons(v){['tf-deep','tf-challenge','tf-repair','tf-export'].forEach(function(id){var b=document.getElementById(id);if(b)b.disabled=v;});}
function addProofButtons(root){(root||document).querySelectorAll('.acts:not([data-truth])').forEach(function(a){a.dataset.truth='1';var b=document.createElement('button');b.className='act tf-proof-act';b.title='Truth Forge: audit this answer';b.innerHTML='⚖ Proof';b.onclick=function(){open(a.dataset.q||'',a.dataset.raw||'');};a.appendChild(b);});}
function openLatest(){var all=document.querySelectorAll('.acts[data-raw]');if(!all.length){if(typeof toast==='function')toast('Pehle Damru se ek answer lo');return;}var a=all[all.length-1];open(a.dataset.q||'',a.dataset.raw||'');}
function init(){injectCSS();modal();addProofButtons(document);var chat=document.getElementById('chat');if(chat)new MutationObserver(function(){addProofButtons(chat);}).observe(chat,{childList:true,subtree:true});var sb=document.querySelector('.sb');if(sb&&!document.getElementById('tf-nav')){var b=document.createElement('button');b.id='tf-nav';b.className='navbtn tf-nav';b.innerHTML='<span class="ic">'+chakra(19,'pulse')+'</span> Truth Forge <span class="tf-new">NEW</span>';b.onclick=openLatest;var sec=sb.querySelector('.sb-sec');sb.insertBefore(b,sec||sb.children[1]);}}
window.DamruTruthForge={open:open,openLatest:openLatest,deepAudit:function(){return deep(false);},challenge:function(){return deep(true);},repair:repair,localAudit:localAudit};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
