/* DAMRU UNIVERSE SIM v1 — live Earth/space/chemistry/biology coarse simulation + AI preflight */
(function(){'use strict';if(window.DamruUniverseSim)return;
var SIM={running:false,raf:0,t:0,last:0,velocity:null,snap:null,internal:[],report:null};
var ENV={earth:{name:'Earth atmosphere',g:9.80665,rho:1.225,temp:288.15,wind:2,drag:.47,bounce:.18,color:'#07111f'},moon:{name:'Moon vacuum',g:1.62,rho:0,temp:220,wind:0,drag:.47,bounce:.08,color:'#090b12'},mars:{name:'Mars atmosphere',g:3.711,rho:.020,temp:210,wind:8,drag:.47,bounce:.12,color:'#1a0b08'},space:{name:'Orbital vacuum',g:0,rho:0,temp:3,wind:0,drag:.47,bounce:0,color:'#010207'},underwater:{name:'Earth water',g:9.80665,rho:997,temp:293,wind:.3,drag:.82,bounce:.05,color:'#031423'},chemistry:{name:'Molecular thermal bath',g:0,rho:0,temp:298,wind:0,drag:.2,bounce:0,color:'#030711'},biology:{name:'Cellular aqueous bath',g:0,rho:997,temp:310,wind:0,drag:.9,bounce:0,color:'#050815'}};
function q(id){return document.getElementById(id)}function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}function st(){var d=window.DamruVisualise;if(!d||!d.state||!d.state.root||!d.state.built)throw Error('Build a Visualise model first');return d.state}
function css(){if(q('dus-css'))return;var s=document.createElement('style');s.id='dus-css';s.textContent=`#dus{position:fixed;inset:0;z-index:130000;background:rgba(1,3,8,.9);backdrop-filter:blur(12px);display:none;align-items:center;justify-content:center;padding:12px;color:#edf3ff;font-family:Inter,system-ui}#dus.on{display:flex}.dus-card{width:min(1060px,100%);max-height:95dvh;overflow:auto;background:linear-gradient(145deg,#111a2c,#080d17);border:1px solid #32415e;border-radius:18px;box-shadow:0 30px 100px #000}.dus-head{display:flex;gap:10px;align-items:center;padding:14px 16px;border-bottom:1px solid #263149}.dus-head h2{font-size:18px;margin:0;flex:1}.dus-head small{display:block;color:#8495b7;font-size:10px}.dus-x,.dus-btn{border:1px solid #3a4968;background:#1d2940;color:#fff;border-radius:9px;padding:8px 11px;cursor:pointer}.dus-btn.main{background:#315fcb}.dus-btn.good{background:#14704c}.dus-btn.stop{background:#7c2732}.dus-grid{display:grid;grid-template-columns:280px 1fr;gap:12px;padding:14px}.dus-panel{border:1px solid #283650;background:rgba(255,255,255,.025);border-radius:13px;padding:12px}.dus-panel h3{font-size:12px;color:#a9bad9;margin:0 0 10px}.dus-field{display:grid;grid-template-columns:1fr 100px;gap:7px;align-items:center;font-size:11px;margin:8px 0}.dus-field select,.dus-field input{width:100%;box-sizing:border-box;background:#111a29;color:#fff;border:1px solid #344362;border-radius:7px;padding:7px}.dus-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.dus-kpi{padding:9px;background:#111a29;border-radius:9px}.dus-kpi b{display:block;font-size:15px}.dus-kpi span{font-size:9px;color:#8295ba}.dus-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:11px}.dus-log{min-height:124px;max-height:260px;overflow:auto;font:11px/1.55 ui-monospace,monospace;color:#9eb4dc;white-space:pre-wrap}.dus-eq{font:11px/1.6 ui-monospace,monospace;background:#080e1a;padding:9px;border-radius:9px;color:#78a5ff}.dus-warn{margin:0 14px 14px;padding:10px;border:1px solid #6a562a;background:#2b220c;color:#dec887;border-radius:10px;font-size:10px}.dus-ai{display:grid;gap:7px}.dus-chip{border-left:3px solid #5e88ec;background:#10192a;padding:8px;border-radius:6px;font-size:11px}@media(max-width:760px){.dus-grid{grid-template-columns:1fr}.dus-kpis{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(s)}
function modal(){if(q('dus'))return;css();var m=document.createElement('div');m.id='dus';m.innerHTML=`<div class="dus-card"><div class="dus-head"><span style="font-size:25px">🌌</span><h2>Damru Universe Sim<small>reasoning-driven Earth · space · chemistry · biology digital twin</small></h2><button class="dus-x">×</button></div><div class="dus-grid"><div class="dus-panel"><h3>ENVIRONMENT</h3><div class="dus-field"><label>World</label><select id="dus-env">${Object.keys(ENV).map(function(k){return'<option value="'+k+'">'+ENV[k].name+'</option>'}).join('')}</select></div><div class="dus-field"><label>Material</label><select id="dus-mat"><option value="1200">polymer</option><option value="7800">steel</option><option value="2700">aluminium</option><option value="4500">titanium</option><option value="1000">biological/water</option><option value="500">custom light</option></select></div><div class="dus-field"><label>Time scale</label><input id="dus-time" type="range" min=".05" max="2" value=".35" step=".05"></div><div class="dus-field"><label>Temperature K</label><input id="dus-temp" type="number" value="288"></div><div class="dus-field"><label>Wind/fluid m·s⁻¹</label><input id="dus-wind" type="number" value="2" step=".1"></div><div class="dus-field"><label>Drag coefficient</label><input id="dus-cd" type="number" value=".47" step=".01"></div><div class="dus-actions"><button class="dus-btn main" id="dus-run">▶ Run</button><button class="dus-btn stop" id="dus-pause">Ⅱ Pause</button><button class="dus-btn" id="dus-reset">↺ Reset</button><button class="dus-btn good" id="dus-ai">🧠 Damru preflight</button></div></div><div><div class="dus-panel"><h3>LIVE MATHEMATICAL STATE</h3><div class="dus-kpis"><div class="dus-kpi"><b id="dus-mass">—</b><span>estimated mass kg</span></div><div class="dus-kpi"><b id="dus-speed">0</b><span>visual speed m/s</span></div><div class="dus-kpi"><b id="dus-force">0</b><span>net force N</span></div><div class="dus-kpi"><b id="dus-energy">0</b><span>energy J</span></div></div><div class="dus-eq" id="dus-eq">F = m·a · Fdrag = ½ρCdAv² · semi-implicit Euler</div></div><div class="dus-panel" style="margin-top:12px"><h3>DAMRU REASONING + EVENT LOG</h3><div class="dus-log" id="dus-log">Transfer a model and select an environment.</div><div class="dus-ai" id="dus-report"></div></div></div></div><div class="dus-warn"><b>Honest scope:</b> interactive coarse digital twin. Rigid assembly uses approximate bounding volume, drag and collision; chemistry/biology use visual harmonic-bond and thermal-motion models. This is not certified FEM/CFD, quantum chemistry, protein-fold prediction, clinical evidence or a substitute for physical testing.</div></div>`;document.body.appendChild(m);bind()}
function bounds(){var S=st();if(window.DamruSimLab&&DamruSimLab.bounds)return DamruSimLab.bounds(S.root);var b=new THREE.Box3().setFromObject(S.root),z=b.getSize(new THREE.Vector3());return{min:b.min,max:b.max,size:z,meshes:S.selectable.length,tris:0}}
function config(){var k=q('dus-env').value,e=Object.assign({},ENV[k]);e.key=k;e.temp=+q('dus-temp').value||e.temp;e.wind=+q('dus-wind').value||0;e.drag=+q('dus-cd').value||e.drag;e.density=+q('dus-mat').value||1200;e.time=+q('dus-time').value||.35;return e}
function estimate(e){var b=bounds(),vol=Math.max(.000001,b.size.x*b.size.y*b.size.z*.36),mass=Math.max(.001,vol*e.density),area=Math.max(.001,b.size.x*b.size.z);return{bounds:b,volume:vol,mass:mass,area:area}}
function n(x){if(!isFinite(x))return'—';if(Math.abs(x)>=1e6)return x.toExponential(2);return(Math.round(x*100)/100).toLocaleString()}
function capture(){var S=st();SIM.snap={root:{p:S.root.position.clone(),r:S.root.rotation.clone()},parts:[]};S.root.traverse(function(o){if(o!==S.root)SIM.snap.parts.push({o:o,p:o.position.clone(),r:o.rotation.clone()})});SIM.internal=SIM.snap.parts.filter(function(x){var n=(x.o.name||'').toLowerCase();return /base-|phosphate|sugar|backbone|hydrogen|residue|side-chain|peptide| atom |bond|c-h|c-o|ring-/.test(n)});SIM.velocity=new THREE.Vector3(0,0,0);SIM.t=0}
function reset(){pause();if(!SIM.snap)return;var S=st();S.root.position.copy(SIM.snap.root.p);S.root.rotation.copy(SIM.snap.root.r);SIM.snap.parts.forEach(function(x){if(x.o.parent){x.o.position.copy(x.p);x.o.rotation.copy(x.r)}});SIM.velocity.set(0,0,0);SIM.t=0;log('State reset to transfer snapshot.');update()}
function internalStep(e,t){var T=Math.max(1,e.temp),amp=(e.key==='biology'?.022:e.key==='chemistry'?.038:.008)*Math.sqrt(T/298);SIM.internal.forEach(function(x,i){if(!x.o.parent)return;var phase=i*2.399+x.p.x*.31;x.o.position.x=x.p.x+Math.sin(t*2.1+phase)*amp;x.o.position.y=x.p.y+Math.cos(t*1.7+phase)*amp*.72;x.o.position.z=x.p.z+Math.sin(t*2.7+phase)*amp*.85;});}
function rigidStep(e,dt){var S=st(),m=estimate(e),v=SIM.velocity,g=e.g,vy=v.y,dragY=.5*e.rho*e.drag*m.area*vy*Math.abs(vy),buoy=e.key==='underwater'?e.rho*m.volume*g:0,Fy=-m.mass*g-dragY+buoy;v.y+=Fy/m.mass*dt;var rel=e.wind-v.x,Fx=.5*e.rho*e.drag*Math.max(.001,m.bounds.size.y*m.bounds.size.z)*rel*Math.abs(rel);v.x+=Fx/m.mass*dt;S.root.position.addScaledVector(v,dt);S.root.rotation.y+=dt*(e.key==='space'?.12:.012);var b=bounds();if(e.key!=='space'&&e.key!=='chemistry'&&e.key!=='biology'&&b.min.y<0){S.root.position.y-=b.min.y;v.y=Math.abs(v.y)*e.bounce;if(Math.abs(v.y)<.08)v.y=0;log('Ground/fluid boundary contact resolved.');}SIM.report={e:e,m:m,Fy:Fy,Fx:Fx,energy:.5*m.mass*v.lengthSq()+m.mass*g*Math.max(0,S.root.position.y)};}
function tick(now){if(!SIM.running)return;var e=config(),dt=Math.min(.035,(now-SIM.last)/1000||.016)*e.time;SIM.last=now;SIM.t+=dt;if(e.key==='chemistry'||e.key==='biology'){internalStep(e,SIM.t);SIM.report={e:e,m:estimate(e),Fy:0,Fx:0,energy:1.5*1.380649e-23*e.temp*Math.max(1,SIM.internal.length)};}else rigidStep(e,dt);update();SIM.raf=requestAnimationFrame(tick)}
function run(){try{st();if(!SIM.snap)capture();if(SIM.running)return;SIM.running=true;SIM.last=performance.now();log('Simulation started: '+config().name);SIM.raf=requestAnimationFrame(tick);if(window.DamruChakra)DamruChakra.setState('building','SIMULATE')}catch(e){alert(e.message)}}
function pause(){SIM.running=false;if(SIM.raf)cancelAnimationFrame(SIM.raf);SIM.raf=0;if(window.DamruChakra)DamruChakra.setState('ready','READY');log('Simulation paused.')}
function update(){if(!SIM.report){var e=config(),m=estimate(e);SIM.report={e:e,m:m,Fy:-m.mass*e.g,Fx:0,energy:0}}var r=SIM.report,v=SIM.velocity||new THREE.Vector3();q('dus-mass').textContent=n(r.m.mass);q('dus-speed').textContent=n(v.length());q('dus-force').textContent=n(Math.sqrt(r.Fy*r.Fy+r.Fx*r.Fx));q('dus-energy').textContent=n(r.energy);var mode=r.e.key==='chemistry'?'Harmonic bonds + kBT thermal motion':r.e.key==='biology'?'Coarse DNA/protein thermal dynamics at '+r.e.temp+' K':'F=m·a | Fdrag=½ρCdAv² | g='+r.e.g+' | ρ='+r.e.rho;q('dus-eq').textContent=mode;}
function log(x){var l=q('dus-log');if(!l)return;var line='['+new Date().toLocaleTimeString()+'] '+x;l.textContent=(line+'\n'+l.textContent).slice(0,5000)}
function parseJSON(x){var m=String(x||'').match(/```(?:json)?\s*([\s\S]*?)```/i);x=m?m[1]:String(x||'');var a=x.indexOf('{'),b=x.lastIndexOf('}');if(a<0||b<a)throw Error('No JSON');return JSON.parse(x.slice(a,b+1).replace(/,\s*([}\]])/g,'$1'))}
async function preflight(){var S=st(),e=config(),m=estimate(e),out=q('dus-report');out.innerHTML='<div class="dus-chip">Damru is reasoning across geometry, environment, physics and domain constraints…</div>';if(window.DamruChakra)DamruChakra.setState('verify','SIM REASON');try{if(typeof window.__damruLLM!=='function')throw Error('Damru intelligence bridge unavailable');var payload={model:S.lastSpec&&{name:S.lastSpec.name,units:S.lastSpec.units,metadata:S.lastSpec.metadata,simulation:S.lastSpec.simulation,partCount:S.selectable.length},environment:e,estimated:{massKg:m.mass,bounds:m.bounds.size,volume:m.volume},scope:'coarse browser digital twin'};var sys='You are Damru Universe Simulation Architect. Return ONLY strict JSON: {summary:string,assumptions:[string],equations:[string],physics:[string],chemistry:[string],biology:[string],failure_modes:[string],recommended_tests:[string]}. Reason from the provided model and environment. Never claim FEM, CFD, quantum, clinical, experimental or certified results. Explicitly mark inapplicable domains instead of inventing effects.';var raw=await window.__damruLLM([{role:'system',content:sys},{role:'user',content:JSON.stringify(payload)}],2200),r=parseJSON(raw);SIM.ai=r;out.innerHTML='<div class="dus-chip"><b>'+esc(r.summary||'Preflight complete')+'</b></div>'+['assumptions','equations','physics','chemistry','biology','failure_modes','recommended_tests'].map(function(k){var a=r[k]||[];return a.length?'<div class="dus-chip"><b>'+esc(k.replace('_',' '))+'</b><br>'+a.map(esc).join('<br>')+'</div>':''}).join('');log('Damru AI preflight completed without claiming certification.')}catch(e){out.innerHTML='<div class="dus-chip">AI preflight unavailable: '+esc(e.message||e)+'. Deterministic simulator remains active.</div>'}finally{if(window.DamruChakra)DamruChakra.setState('ready','READY')}}
function transfer(){pause();capture();var e=config(),meta=st().lastSpec&&st().lastSpec.simulation;if(meta&&meta.domain==='biology')q('dus-env').value='biology';else if(meta&&meta.domain==='chemistry')q('dus-env').value='chemistry';syncEnv();SIM.report=null;update();log('Live scene transferred: '+((st().lastSpec&&st().lastSpec.name)||'untitled')+' · '+st().selectable.length+' semantic parts.');}
function syncEnv(){var e=ENV[q('dus-env').value];q('dus-temp').value=e.temp;q('dus-wind').value=e.wind;q('dus-cd').value=e.drag;try{st().scene.background.set(e.color)}catch(x){}update()}
function bind(){q('dus').querySelector('.dus-x').onclick=close;q('dus-run').onclick=run;q('dus-pause').onclick=pause;q('dus-reset').onclick=reset;q('dus-ai').onclick=preflight;q('dus-env').onchange=syncEnv;q('dus').onclick=function(e){if(e.target===this)close()}}
function open(){modal();q('dus').classList.add('on');try{transfer()}catch(e){q('dus-log').textContent=e.message}}
function close(){pause();if(q('dus'))q('dus').classList.remove('on')}
function inject(){var top=q('dv-top');if(top&&!q('dus-launch')){var b=document.createElement('button');b.id='dus-launch';b.className='dv-btn';b.textContent='🌌 Universe Sim';b.onclick=open;var ref=q('dsl-launch')||q('dpf-launch');top.insertBefore(b,ref||null)}}
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});setTimeout(inject,1200);window.DamruUniverseSim={open:open,close:close,run:run,pause:pause,reset:reset,transfer:transfer,preflight:preflight,state:SIM,environments:ENV};
})();
