/* DAMRU SOVEREIGN MIND browser layer — IndexedDB memory + local daemon bridge */
(function(){'use strict';if(window.DamruSovereignMind)return;
var DB='damru-sovereign-v1',VER=1,DAEMON=localStorage.getItem('damru_sovereign_url')||'http://127.0.0.1:8733',TOKEN=localStorage.getItem('damru_sovereign_token')||'',state={db:null,daemon:false,last:null};
function tok(s){return(String(s||'').toLowerCase().match(/[a-z0-9_-]{2,}|[\u0900-\u097f]{2,}/g)||[]).slice(0,80)}function key(q,a){var s=(q+'\n'+a).toLowerCase(),h=2166136261;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
function openDB(){if(state.db)return Promise.resolve(state.db);return new Promise(function(ok,no){var r=indexedDB.open(DB,VER);r.onupgradeneeded=function(){var d=r.result;if(!d.objectStoreNames.contains('episodes')){var s=d.createObjectStore('episodes',{keyPath:'id'});s.createIndex('updated','updated');s.createIndex('verified','verified')}if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta',{keyPath:'k'})};r.onsuccess=function(){state.db=r.result;ok(state.db)};r.onerror=function(){no(r.error)}})}
async function all(store){var d=await openDB();return new Promise(function(ok,no){var r=d.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=function(){ok(r.result||[])};r.onerror=function(){no(r.error)}})}
async function put(store,v){var d=await openDB();return new Promise(function(ok,no){var r=d.transaction(store,'readwrite').objectStore(store).put(v);r.onsuccess=function(){ok(v)};r.onerror=function(){no(r.error)}})}
function sensitive(s){return/(?:hf_|gsk_|sk-)[A-Za-z0-9._-]{12,}|(?:password|api[_ -]?key|token)\s*[:=]\s*\S+/i.test(s)}
async function learn(q,a,source,verified,score){q=String(q||'').trim();a=String(a||'').trim();if(q.length<3||a.length<8||sensitive(q+'\n'+a))return{accepted:false};var id=key(q,a),xs=await all('episodes'),old=xs.find(function(x){return x.id===id}),uses=(old&&old.uses||0)+1,e={id:id,q:q.slice(0,12000),a:a.slice(0,30000),source:source||'browser',verified:!!(verified||(old&&old.verified)),score:Math.min(1,score==null?(old?((old.score*old.uses+.55)/uses):.55):score),uses:uses,created:old&&old.created||Date.now(),updated:Date.now()};await put('episodes',e);daemon('/learn',{question:q,answer:a,source:e.source,verified:e.verified,score:e.score},1800).catch(function(){});return{accepted:true,id:id}}
async function recall(q,limit){var qt=new Set(tok(q)),xs=await all('episodes');xs.forEach(function(x){var xt=new Set(tok(x.q)),hit=0;qt.forEach(function(t){if(xt.has(t))hit++});var lex=hit/Math.max(1,new Set([].concat(Array.from(qt),Array.from(xt))).size);x._rank=.5*(x.score||.5)+.25*(x.verified?1:0)+.15*Math.min(1,(x.uses||1)/5)+.1*lex});return xs.filter(function(x){return x._rank>.28}).sort(function(a,b){return b._rank-a._rank}).slice(0,limit||6)}
async function daemon(path,body,ms){var c=new AbortController(),t=setTimeout(function(){c.abort()},ms||6500);try{var h={'Content-Type':'application/json'};if(TOKEN)h['X-Damru-Token']=TOKEN;var r=await fetch(DAEMON+path,{method:'POST',headers:h,body:JSON.stringify(body||{}),signal:c.signal});if(!r.ok)throw Error('sovereign '+r.status);state.daemon=true;return await r.json()}finally{clearTimeout(t)}}
async function health(){try{var c=new AbortController(),t=setTimeout(function(){c.abort()},1500),r=await fetch(DAEMON+'/health',{signal:c.signal});clearTimeout(t);state.daemon=!!r.ok;return r.ok?await r.json():null}catch(e){state.daemon=false;return null}}
async function prepare(messages){var last=[].concat(messages).reverse().find(function(x){return x.role==='user'}),q=last&&last.content||'',mem=await recall(q,5);if(!mem.length)return messages;var ctx='DAMRU SOVEREIGN BROWSER MEMORY (untrusted hints; verify before use):\n'+mem.map(function(x){return '- Q: '+x.q.slice(0,350)+'\n  A: '+x.a.slice(0,900)+'\n  verified='+x.verified+' readiness='+x._rank.toFixed(2)}).join('\n');return[{role:'system',content:ctx}].concat(messages)}
async function route(messages,maxTokens,temp,intent){var last=[].concat(messages).reverse().find(function(x){return x.role==='user'}),q=last&&last.content||'',mem=await recall(q,4),exact=mem.find(function(x){return x.verified&&x._rank>=.76&&x.q.trim().toLowerCase()===q.trim().toLowerCase()});if(exact){state.last={source:'sovereign-memory',id:exact.id};return{answer:exact.a,source:'sovereign-memory'}}try{var d=await daemon('/answer',{messages:await prepare(messages),max_tokens:maxTokens||1000},intent==='code'||intent==='math'?12000:7000);if(d&&d.answer){state.last=d;return{answer:d.answer,source:d.provider||'sovereign-local'}}}catch(e){}return null}
async function feedback(id,positive){var xs=await all('episodes'),e=xs.find(function(x){return x.id===id});if(!e)return false;e.score=Math.max(0,Math.min(1,(e.score||.5)+(positive?.16:-.28)));e.verified=!!(positive&&e.score>=.72);e.updated=Date.now();await put('episodes',e);daemon('/feedback',{digest:id,positive:positive},1800).catch(function(){});return true}
async function consolidate(){var xs=await all('episodes'),cut=Date.now()-30*864e5;xs=xs.filter(function(x){return x.verified||x.score>=.18||x.updated>cut});var d=await openDB(),tx=d.transaction('episodes','readwrite'),st=tx.objectStore('episodes');st.clear();xs.slice(-1500).forEach(function(x){delete x._rank;st.put(x)});daemon('/consolidate',{},2500).catch(function(){});return xs.length}
function css(){if(document.getElementById('dsm-css'))return;var s=document.createElement('style');s.id='dsm-css';s.textContent='#dsm-hud{position:fixed;left:12px;bottom:84px;z-index:8999;background:rgba(8,16,30,.92);border:1px solid #2d4e86;color:#a8c8ff;border-radius:12px;padding:7px 10px;font:10px Inter,system-ui;cursor:pointer;box-shadow:0 8px 30px #0008}#dsm-hud b{color:#fff}';document.head.appendChild(s)}
async function hud(){css();var e=document.getElementById('dsm-hud');if(!e){e=document.createElement('button');e.id='dsm-hud';e.onclick=async function(){var x=await all('episodes'),h=await health();alert('Sovereign Mind\nBrowser memories: '+x.length+'\nLocal daemon: '+(h?'online':'offline')+'\nEmergency Pollinations: '+(localStorage.getItem('damru_emergency_backup')==='1'?'ON':'OFF'));};document.body.appendChild(e)}var xs=await all('episodes');e.innerHTML='<b>🧠 Sovereign</b> · '+xs.length+' memories · '+(state.daemon?'local on':'browser')}
function init(){openDB().then(hud).catch(function(){});health().then(hud);setInterval(function(){consolidate().then(hud)},5*60*1000);if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('/damru_sovereign_sw.js').catch(function(){})}
window.DamruSovereignMind={route:route,prepare:prepare,learn:learn,recall:recall,feedback:feedback,consolidate:consolidate,health:health,state:state,setDaemon:function(u,t){DAEMON=u;TOKEN=t||'';localStorage.setItem('damru_sovereign_url',u);if(t)localStorage.setItem('damru_sovereign_token',t)}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
