/* DAMRU PRINT FORGE v1.0
 * Browser control panel for local damru_print_bridge.py.
 * Physical printing is NEVER automatic: connection test + G-code preflight +
 * checkbox + exact PRINT confirmation are required.
 */
(function(){
'use strict';
if(window.DamruPrintForge)return;
var P={bridge:'http://127.0.0.1:8732',token:'',provider:'octoprint',printerUrl:'http://octopi.local',apiKey:'',fileId:'',fileName:'',needsSlice:false,jobId:'',timer:null,preflight:null,busy:false};
function q(id){return document.getElementById(id)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
function css(){if(q('dpf-css'))return;var s=document.createElement('style');s.id='dpf-css';s.textContent=''
+'#dpf-modal{position:fixed;inset:0;z-index:100500;background:rgba(4,6,10,.88);display:none;align-items:center;justify-content:center;font-family:Inter,system-ui;color:#e9edf7;padding:14px}'
+'#dpf-modal.on{display:flex}#dpf-card{width:min(760px,100%);max-height:94vh;overflow:auto;background:#10141e;border:1px solid #2c3550;border-radius:16px;box-shadow:0 24px 80px #000;padding:16px}'
+'.dpf-head{display:flex;align-items:center;gap:10px;margin-bottom:12px}.dpf-head h2{font-size:18px;margin:0;flex:1}.dpf-x{font-size:20px}'
+'.dpf-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.dpf-wide{grid-column:1/-1}.dpf-box{background:#0b0e15;border:1px solid #242b3d;border-radius:12px;padding:12px}.dpf-box h3{font-size:13px;margin:0 0 9px;color:#aeb8d3}'
+'.dpf-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:7px 0}.dpf-row label{font-size:12px;color:#9ca6bf}.dpf-in,.dpf-sel{min-width:0;flex:1;background:#151b28;color:#fff;border:1px solid #303a55;border-radius:8px;padding:9px}.dpf-btn{background:#202a40;color:#fff;border:1px solid #35425f;border-radius:9px;padding:9px 12px;cursor:pointer}.dpf-btn:hover{background:#2b3856}.dpf-primary{background:#e8623d;border-color:#e8623d}.dpf-danger{background:#a92835;border-color:#d34251}.dpf-btn:disabled{opacity:.45;cursor:not-allowed}'
+'#dpf-log{white-space:pre-wrap;font:12px/1.45 ui-monospace,monospace;background:#080a10;border-radius:9px;padding:9px;min-height:58px;max-height:150px;overflow:auto;color:#aeb8d3}'
+'.dpf-progress{height:13px;background:#262d3d;border-radius:20px;overflow:hidden}.dpf-progress>i{display:block;height:100%;width:0;background:linear-gradient(90deg,#e8623d,#ffb44c);transition:.4s}.dpf-kpi{display:flex;justify-content:space-between;font-size:12px;color:#aeb8d3;margin-top:6px}.dpf-warn{color:#ffbd64;font-size:12px}.dpf-ok{color:#62d99a}.dpf-bad{color:#ff7180}'
+'@media(max-width:700px){.dpf-grid{grid-template-columns:1fr}.dpf-wide{grid-column:auto}#dpf-card{padding:12px}.dpf-row{align-items:stretch}.dpf-btn{min-height:42px}}';document.head.appendChild(s)}
function html(){if(q('dpf-modal'))return;css();var m=document.createElement('div');m.id='dpf-modal';m.innerHTML='<div id="dpf-card">'
+'<div class="dpf-head"><span style="font-size:26px">🖨️</span><h2>Damru Print Forge <small style="color:#7f8aa6;font-weight:500">local & safe</small></h2><button class="dpf-btn dpf-x" id="dpf-close">×</button></div>'
+'<div class="dpf-grid">'
+'<section class="dpf-box dpf-wide"><h3>1 · Local Bridge</h3><div class="dpf-row"><input class="dpf-in" id="dpf-bridge" placeholder="http://127.0.0.1:8732"><input class="dpf-in" id="dpf-token" type="password" placeholder="Bridge token"><button class="dpf-btn" id="dpf-health">Check Bridge</button></div><div class="dpf-warn">Run <code>python damru_print_bridge.py</code> on the computer attached to the printer. Token stays in this browser session.</div></section>'
+'<section class="dpf-box"><h3>2 · Printer connection</h3><div class="dpf-row"><select class="dpf-sel" id="dpf-provider"><option value="octoprint">OctoPrint</option><option value="moonraker">Klipper / Moonraker</option></select></div><div class="dpf-row"><input class="dpf-in" id="dpf-printer" placeholder="http://octopi.local"></div><div class="dpf-row"><input class="dpf-in" id="dpf-key" type="password" placeholder="API key (if required)"><button class="dpf-btn" id="dpf-test">Connect</button></div></section>'
+'<section class="dpf-box"><h3>3 · Model source</h3><div class="dpf-row"><button class="dpf-btn" id="dpf-current">Use current Visualise model</button><button class="dpf-btn" id="dpf-pick">Choose from computer</button><input id="dpf-file" type="file" accept=".stl,.3mf,.obj,.gcode,.gco,.gc" hidden></div><div id="dpf-file-name" style="font-size:12px;color:#9ca6bf">No file uploaded</div><div class="dpf-row"><input class="dpf-in" id="dpf-profile" placeholder="Optional local PrusaSlicer .ini path"><button class="dpf-btn" id="dpf-slice" disabled>Slice</button></div></section>'
+'<section class="dpf-box dpf-wide"><h3>4 · Safety preflight</h3><div class="dpf-row"><label>Build X</label><input class="dpf-in" id="dpf-x" type="number" value="220"><label>Y</label><input class="dpf-in" id="dpf-y" type="number" value="220"><label>Z</label><input class="dpf-in" id="dpf-z" type="number" value="250"></div><div class="dpf-row"><label>Max nozzle °C</label><input class="dpf-in" id="dpf-nozzle" type="number" value="300"><label>Max bed °C</label><input class="dpf-in" id="dpf-bed" type="number" value="130"><button class="dpf-btn" id="dpf-preflight" disabled>Run preflight</button></div><div id="dpf-preflight-out" class="dpf-warn">No G-code verified yet.</div></section>'
+'<section class="dpf-box dpf-wide"><h3>5 · Print with explicit confirmation</h3><div class="dpf-warn">Stay near the printer during first layers. Check bed, filament, nozzle clearance and emergency power access. Damru never starts a print silently.</div><div class="dpf-row"><label><input type="checkbox" id="dpf-check"> I inspected the printer and accept physical operation</label><input class="dpf-in" id="dpf-confirm" placeholder="Type PRINT"><button class="dpf-btn dpf-primary" id="dpf-start" disabled>Start physical print</button><button class="dpf-btn dpf-danger" id="dpf-cancel" disabled>Emergency cancel</button></div><div class="dpf-progress"><i id="dpf-bar"></i></div><div class="dpf-kpi"><span id="dpf-state">Idle</span><span id="dpf-pct">0%</span><span id="dpf-eta">ETA —</span></div></section>'
+'<section class="dpf-box dpf-wide"><h3>Live event log</h3><div id="dpf-log">Print Forge ready.</div></section>'
+'</div></div>';document.body.appendChild(m);bind();loadSession()}
function log(s,kind){var e=q('dpf-log');var line='['+new Date().toLocaleTimeString()+'] '+s;e.textContent=line+'\n'+e.textContent;if(kind)e.className=kind}
function cfg(){return{provider:q('dpf-provider').value,url:q('dpf-printer').value.trim(),apiKey:q('dpf-key').value.trim()}}
function limits(){return{maxNozzle:+q('dpf-nozzle').value,maxBed:+q('dpf-bed').value,volume:{x:+q('dpf-x').value,y:+q('dpf-y').value,z:+q('dpf-z').value}}}
function sync(){P.bridge=q('dpf-bridge').value.replace(/\/$/,'');P.token=q('dpf-token').value;P.provider=q('dpf-provider').value;P.printerUrl=q('dpf-printer').value;P.apiKey=q('dpf-key').value;try{sessionStorage.setItem('damru_print_session',JSON.stringify({bridge:P.bridge,token:P.token,provider:P.provider,printerUrl:P.printerUrl,apiKey:P.apiKey,fileId:P.fileId,fileName:P.fileName,needsSlice:P.needsSlice,jobId:P.jobId}))}catch(e){}}
function loadSession(){try{var x=JSON.parse(sessionStorage.getItem('damru_print_session')||'{}');Object.assign(P,x)}catch(e){}q('dpf-bridge').value=P.bridge;q('dpf-token').value=P.token;q('dpf-provider').value=P.provider;q('dpf-printer').value=P.printerUrl;q('dpf-key').value=P.apiKey;if(P.fileName)q('dpf-file-name').textContent=P.fileName+' · restored session';if(P.jobId){q('dpf-cancel').disabled=false;q('dpf-state').textContent='reconnecting…'}}
async function req(path,opt){sync();opt=opt||{};opt.headers=Object.assign({'X-Damru-Bridge-Token':P.token},opt.headers||{});var c=new AbortController(),t=setTimeout(function(){c.abort()},opt.timeout||30000);opt.signal=c.signal;try{var r=await fetch(P.bridge+path,opt),d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||('HTTP '+r.status));return d}finally{clearTimeout(t)}}
function post(path,obj,timeout){return req(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj),timeout:timeout||30000})}
async function health(){try{var d=await req('/health',{timeout:5000});log('Bridge online v'+d.version+' · slicer '+(d.slicer&&d.slicer.prusa?'PrusaSlicer ready':'not found'),'dpf-ok')}catch(e){log('Bridge unavailable: '+e.message,'dpf-bad')}}
async function testPrinter(){try{var d=await post('/printer/test',{printer:cfg()});log('Connected to '+d.provider,'dpf-ok')}catch(e){log('Printer connection failed: '+e.message,'dpf-bad')}}
async function upload(blob,name){if(P.busy)return;P.busy=true;try{log('Uploading '+name+' to local bridge…');var d=await req('/files',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Filename':name},body:blob,timeout:180000});P.fileId=d.fileId;P.fileName=d.name;P.needsSlice=d.needsSlice;P.preflight=null;q('dpf-file-name').textContent=d.name+' · '+Math.round(d.size/1024)+' KB'+(d.needsSlice?' · slicing required':' · G-code');q('dpf-slice').disabled=!d.needsSlice;q('dpf-preflight').disabled=d.needsSlice;q('dpf-start').disabled=true;log('File secured in local spool','dpf-ok');if(!d.needsSlice)await preflight()}catch(e){log('Upload failed: '+e.message,'dpf-bad')}finally{P.busy=false}}
async function currentModel(){try{if(!window.DamruVisualise||!window.DamruVisualise.getSTLBlob)throw new Error('Build a Visualise model first');var b=window.DamruVisualise.getSTLBlob();if(!b)throw new Error('Nothing to print');await upload(b,'damru-visualise.stl')}catch(e){log(e.message,'dpf-bad')}}
async function slice(){try{q('dpf-slice').disabled=true;log('Local slicer running…');var d=await post('/slice',{fileId:P.fileId,profile:q('dpf-profile').value.trim()||null,limits:limits()},920000);P.fileId=d.fileId;P.needsSlice=false;P.preflight=d.preflight;q('dpf-file-name').textContent=d.name+' · sliced G-code';renderPreflight(d.preflight);q('dpf-preflight').disabled=false;log('Slicing complete','dpf-ok')}catch(e){log('Slice failed: '+e.message,'dpf-bad')}finally{q('dpf-slice').disabled=!P.needsSlice}}
async function preflight(){try{var d=await post('/preflight',{fileId:P.fileId,limits:limits()},60000);P.preflight=d.preflight;renderPreflight(P.preflight)}catch(e){P.preflight=null;renderPreflight({ok:false,violations:[e.message]})}}
function renderPreflight(p){var e=q('dpf-preflight-out');if(p&&p.ok){e.className='dpf-ok';e.textContent='PASS · nozzle '+p.nozzleMax+'°C · bed '+p.bedMax+'°C · '+p.lines+' lines · SHA '+p.sha256.slice(0,12);q('dpf-start').disabled=false;log('Safety preflight PASS','dpf-ok')}else{e.className='dpf-bad';e.textContent='BLOCKED · '+((p&&p.violations)||['unknown error']).join(' | ');q('dpf-start').disabled=true;log('Safety preflight BLOCKED','dpf-bad')}}
async function start(){if(!P.preflight||!P.preflight.ok)return log('Run passing preflight first','dpf-bad');if(!q('dpf-check').checked||q('dpf-confirm').value!=='PRINT')return log('Check acknowledgement and type exact PRINT','dpf-bad');if(!confirm('Start physical 3D print now? Confirm printer area is clear.'))return;try{q('dpf-start').disabled=true;var d=await post('/print',{fileId:P.fileId,printer:cfg(),limits:limits(),confirmation:'PRINT'},180000);P.jobId=d.job.id;sync();q('dpf-cancel').disabled=false;log('Physical print started · job '+P.jobId,'dpf-ok');poll()}catch(e){log('Print start blocked: '+e.message,'dpf-bad');q('dpf-start').disabled=false}}
function fmt(s){if(s==null)return'—';s=Math.max(0,Math.round(+s));return Math.floor(s/3600)+'h '+Math.floor((s%3600)/60)+'m'}
async function poll(){clearTimeout(P.timer);if(!P.jobId)return;try{var d=await req('/jobs/'+P.jobId,{timeout:10000}),j=d.job||{};var pc=Math.max(0,Math.min(100,+j.progress||0));q('dpf-bar').style.width=pc+'%';q('dpf-pct').textContent=pc.toFixed(1)+'%';q('dpf-state').textContent=j.state||'printing';q('dpf-eta').textContent='ETA '+fmt(j.remaining);if(j.error)log('Monitor warning: '+j.error,'dpf-warn');if(['done','cancelled','error'].indexOf(j.state)>=0){q('dpf-cancel').disabled=true;log('Job '+j.state,j.state==='done'?'dpf-ok':'dpf-bad');return}}catch(e){log('Progress reconnecting: '+e.message,'dpf-warn')}P.timer=setTimeout(poll,2000)}
async function cancel(){if(!P.jobId||!confirm('Cancel the active physical print?'))return;try{await post('/jobs/'+P.jobId+'/cancel',{});q('dpf-cancel').disabled=true;clearTimeout(P.timer);q('dpf-state').textContent='cancelled';log('Emergency cancel sent','dpf-bad')}catch(e){log('Cancel failed: '+e.message,'dpf-bad')}}
function bind(){q('dpf-close').onclick=close;q('dpf-health').onclick=health;q('dpf-test').onclick=testPrinter;q('dpf-current').onclick=currentModel;q('dpf-pick').onclick=function(){q('dpf-file').click()};q('dpf-file').onchange=function(){var f=this.files&&this.files[0];if(f)upload(f,f.name)};q('dpf-slice').onclick=slice;q('dpf-preflight').onclick=preflight;q('dpf-start').onclick=start;q('dpf-cancel').onclick=cancel;q('dpf-modal').onclick=function(e){if(e.target===this)close()}}
function open(){html();q('dpf-modal').classList.add('on');health();if(P.jobId)poll()}
function close(){if(q('dpf-modal'))q('dpf-modal').classList.remove('on')}
function inject(){var top=q('dv-top');if(top&&!q('dpf-launch')){var b=document.createElement('button');b.id='dpf-launch';b.className='dv-btn';b.textContent='🖨 Connect 3D Printer';b.onclick=open;var closeBtn=[].slice.call(top.children).find(function(x){return/Close/.test(x.textContent)});top.insertBefore(b,closeBtn||null)}}
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});setTimeout(inject,1200);
window.DamruPrintForge={open:open,close:close};
})();
