#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
damru_council.py  --  STEP 4 of the Damru 14B Master Plan
=========================================================
Self-play data FACTORY. A council of FREE providers (NVIDIA NIM 32B teacher,
Groq, Cloudflare Workers AI, Mistral, GitHub Models) SOLVES the problems mined
by the Oracle (Step 2). A programmatic VERIFIER (code tests / final-answer
match) and a JUDGE (Gemini) decide what is correct; an EFFICIENCY selector
keeps the shortest passing solution. Accepted, VERIFIED (problem -> solution)
pairs are written to `Damaru-ai/damru-council` for SFT + DPO.

ANTI-COPY: we ingest only PROBLEMS from the oracle. SOLUTIONS are generated by
our own free-provider council and then VERIFIED (RLVR). We never copy a closed
model's chain-of-thought or style. Verifiable rewards > distillation.

6 ROLES: PROPOSER/SOLVER (provider pool) | VERIFIER (tests + answer match) |
CRITIC (reflect-retry, optional) | JUDGE (Gemini) | TRAINER (writes dataset).

Engine = the same v3 core: commit-batching (no HF 429), 429-aware retry,
checkpoint+resume mirrored to the repo, dedup, self time-budget, robust
per-item try/except.

RUN:
  pip install requests "datasets>=2.19" "huggingface_hub>=0.24" "pyarrow>=15"
  export HF_TOKEN=hf_xxx
  # provider keys (any subset; the council uses whatever is present):
  export NVIDIA_NIM_KEY=nvapi-...   GROQ_API_KEY=gsk_...
  export CF_ACCOUNT_ID=...  CF_API_TOKEN=...
  export MISTRAL_API_KEY=...  GEMINI_KEY=...  GH_MODELS_TOKEN=...
  python damru_council.py
"""

import gzip
import hashlib
import json
import logging
import os
import random
import re
import subprocess
import sys
import tempfile
import time
import traceback
from typing import Any, Dict, Iterable, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
OUT_REPO        = os.environ.get("COUNCIL_OUT_REPO", "Damaru-ai/damru-council")
SRC_REPO        = os.environ.get("COUNCIL_SRC_REPO", "Damaru-ai/damru-oracle")
SHARD_ROWS      = int(os.environ.get("COUNCIL_SHARD_ROWS", "2000"))
MAX_PROBLEMS    = int(os.environ.get("COUNCIL_MAX_PROBLEMS", "0"))   # 0 = all
TIME_BUDGET_MIN = int(os.environ.get("COUNCIL_TIME_BUDGET_MIN", "300"))
COMMIT_EVERY    = int(os.environ.get("COUNCIL_COMMIT_EVERY_SEC", "600"))
WORKDIR         = os.environ.get("COUNCIL_WORKDIR", "./council_work")
MIRROR_STATE    = os.environ.get("COUNCIL_MIRROR_STATE", "1") == "1"
HF_TOKEN        = os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_TOKEN")

N_SOLVERS   = int(os.environ.get("COUNCIL_N_SOLVERS", "3"))
REQ_TIMEOUT = int(os.environ.get("COUNCIL_REQ_TIMEOUT", "90"))
MAX_TOKENS  = int(os.environ.get("COUNCIL_MAX_TOKENS", "1024"))
TEMPERATURE = float(os.environ.get("COUNCIL_TEMPERATURE", "0.3"))
CODE_EXEC   = os.environ.get("COUNCIL_CODE_EXEC", "1") == "1"
CODE_TIMEOUT = int(os.environ.get("COUNCIL_CODE_TIMEOUT", "10"))
JUDGE_MIN   = float(os.environ.get("COUNCIL_JUDGE_MIN", "7"))

SPLITS = ("sft", "dpo")
MAX_RETRIES = 6

CKPT_DIR   = os.path.join(WORKDIR, "_ckpt")
DATA_DIR   = os.path.join(WORKDIR, "data")
DL_DIR     = os.path.join(WORKDIR, "_dl")
STATE_PATH = os.path.join(CKPT_DIR, "state.json")
SEEN_PATH  = os.path.join(CKPT_DIR, "seen.txt.gz")
README_PATH = os.path.join(WORKDIR, "README.md")
ERR_PATH   = os.path.join(WORKDIR, "errors.log")

for _d in (WORKDIR, CKPT_DIR, DATA_DIR, DL_DIR):
    os.makedirs(_d, exist_ok=True)
for _s in SPLITS:
    os.makedirs(os.path.join(DATA_DIR, _s), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    handlers=[logging.StreamHandler(sys.stdout),
              logging.FileHandler(os.path.join(WORKDIR, "run.log"))],
)
log = logging.getLogger("council")


def log_error(where: str, exc: Exception) -> None:
    try:
        with open(ERR_PATH, "a", encoding="utf-8") as f:
            f.write(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] {where}: "
                    f"{type(exc).__name__}: {exc}\n")
            f.write(traceback.format_exc() + "\n")
    except Exception:
        pass


def _is_rate_limit(msg: str) -> bool:
    m = msg.lower()
    return "429" in m or "too many requests" in m or "rate limit" in m


def retry(fn, *args, what: str = "op", **kwargs):
    delay = 3.0
    last = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            return fn(*args, **kwargs)
        except Exception as exc:
            last = exc
            msg = str(exc)
            log_error(f"retry:{what}:attempt{attempt}", exc)
            if _is_rate_limit(msg):
                wait = 30.0
                m = re.search(r"retry after (\d+)", msg.lower())
                if m:
                    wait = float(m.group(1)) + 3
                log.warning("[retry] %s rate-limited (%d/%d); sleeping %.0fs",
                            what, attempt, MAX_RETRIES, wait)
                if attempt == MAX_RETRIES:
                    break
                time.sleep(wait)
                continue
            log.warning("[retry] %s failed (%d/%d): %s", what, attempt, MAX_RETRIES, exc)
            if attempt == MAX_RETRIES:
                break
            time.sleep(delay + random.uniform(0, 2.0))
            delay = min(delay * 2, 60.0)
    raise last  # type: ignore[misc]


def atomic_write_text(path: str, text: str) -> None:
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


def sha_id(*parts: str) -> str:
    h = hashlib.sha1()
    for p in parts:
        h.update((p or "").encode("utf-8", "ignore"))
        h.update(b"\x1f")
    return h.hexdigest()[:16]


# ---------------------------------------------------------------------------
# State + seen
# ---------------------------------------------------------------------------
def load_state() -> Dict[str, Any]:
    if os.path.exists(STATE_PATH):
        try:
            with open(STATE_PATH, encoding="utf-8") as f:
                return json.load(f)
        except Exception as exc:
            log_error("load_state", exc)
    return {"version": 1,
            "shard_index": {s: 0 for s in SPLITS},
            "rows_out": {s: 0 for s in SPLITS}, "total_out": 0,
            "problems_done": [], "problems_seen": 0}


def save_state(state: Dict[str, Any]) -> None:
    atomic_write_text(STATE_PATH, json.dumps(state, ensure_ascii=False, indent=2))


def load_seen() -> set:
    seen: set = set()
    if os.path.exists(SEEN_PATH):
        try:
            with gzip.open(SEEN_PATH, "rt", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        seen.add(line)
        except Exception as exc:
            log_error("load_seen", exc)
    log.info("[seen] loaded %d known ids", len(seen))
    return seen


def save_seen(seen: set) -> None:
    tmp = SEEN_PATH + ".tmp"
    try:
        with gzip.open(tmp, "wt", encoding="utf-8") as f:
            for sid in seen:
                f.write(sid + "\n")
        os.replace(tmp, SEEN_PATH)
    except Exception as exc:
        log_error("save_seen", exc)


# ---------------------------------------------------------------------------
# HF client + THROTTLED folder commit (the 429 fix)
# ---------------------------------------------------------------------------
_api = None
_last_commit = [0.0]


def hf_api():
    global _api
    if _api is None:
        from huggingface_hub import HfApi
        _api = HfApi(token=HF_TOKEN)
    return _api


def ensure_repo() -> None:
    def _mk():
        hf_api().create_repo(OUT_REPO, repo_type="dataset", exist_ok=True, private=True)
    retry(_mk, what="create_repo")


def commit_all(force: bool = False) -> None:
    if not force and (time.time() - _last_commit[0] < COMMIT_EVERY):
        return

    def _up():
        hf_api().upload_folder(
            folder_path=WORKDIR, repo_id=OUT_REPO, repo_type="dataset",
            allow_patterns=["data/**", "_ckpt/**", "README.md"],
            commit_message=f"council update {time.strftime('%Y-%m-%d %H:%M:%S')}",
        )
    try:
        retry(_up, what="commit_folder")
        _last_commit[0] = time.time()
        log.info("[commit] uploaded folder snapshot")
    except Exception as exc:
        log_error("commit_all", exc)
        log.warning("[commit] failed -- progress kept locally, will retry later")


def hf_try_download(path_in_repo: str, dest: str) -> bool:
    from huggingface_hub import hf_hub_download
    try:
        from huggingface_hub.utils import EntryNotFoundError
    except Exception:
        class EntryNotFoundError(Exception):
            pass
    delay = 3.0
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            p = hf_hub_download(repo_id=OUT_REPO, repo_type="dataset",
                                filename=path_in_repo, token=HF_TOKEN)
            with open(p, "rb") as src, open(dest, "wb") as out:
                out.write(src.read())
            return True
        except EntryNotFoundError:
            return False
        except Exception as exc:
            msg = str(exc)
            if "404" in msg or "Entry Not Found" in msg or "not found" in msg.lower():
                return False
            log_error(f"download:{path_in_repo}:attempt{attempt}", exc)
            if attempt == MAX_RETRIES:
                return False
            time.sleep(delay + random.uniform(0, 2.0))
            delay = min(delay * 2, 60.0)
    return False


def restore_from_hf() -> None:
    if not MIRROR_STATE:
        return
    if hf_try_download("_ckpt/state.json", STATE_PATH):
        log.info("[resume] restored state.json from HF")
    hf_try_download("_ckpt/seen.txt.gz", SEEN_PATH)


# ---------------------------------------------------------------------------
# Provider council
# ---------------------------------------------------------------------------
def _http_post(url: str, headers: Dict[str, str], payload: Dict[str, Any]) -> Dict[str, Any]:
    import requests
    r = requests.post(url, headers=headers, json=payload, timeout=REQ_TIMEOUT)
    if r.status_code >= 400:
        raise RuntimeError(f"HTTP {r.status_code}: {r.text[:200]}")
    return r.json()


def build_providers() -> List[Dict[str, Any]]:
    provs: List[Dict[str, Any]] = []
    nim = os.environ.get("NVIDIA_NIM_KEY")
    if nim:
        provs.append({"name": "nim", "kind": "openai",
                      "url": "https://integrate.api.nvidia.com/v1/chat/completions",
                      "model": os.environ.get("NIM_MODEL", "qwen/qwen2.5-coder-32b-instruct"),
                      "key": nim, "teacher": True})
    groq = os.environ.get("GROQ_API_KEY")
    if groq:
        provs.append({"name": "groq", "kind": "openai",
                      "url": "https://api.groq.com/openai/v1/chat/completions",
                      "model": os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile"),
                      "key": groq})
    mistral = os.environ.get("MISTRAL_API_KEY")
    if mistral:
        provs.append({"name": "mistral", "kind": "openai",
                      "url": "https://api.mistral.ai/v1/chat/completions",
                      "model": os.environ.get("MISTRAL_MODEL", "mistral-large-latest"),
                      "key": mistral})
    gh = os.environ.get("GH_MODELS_TOKEN")
    if gh:
        provs.append({"name": "github", "kind": "openai",
                      "url": "https://models.inference.ai.azure.com/chat/completions",
                      "model": os.environ.get("GH_MODEL", "gpt-4o-mini"),
                      "key": gh})
    cf_acct = os.environ.get("CF_ACCOUNT_ID")
    cf_tok = os.environ.get("CF_API_TOKEN")
    if cf_acct and cf_tok:
        provs.append({"name": "cloudflare", "kind": "cf",
                      "url": f"https://api.cloudflare.com/client/v4/accounts/{cf_acct}/ai/run/",
                      "model": os.environ.get("CF_MODEL", "@cf/qwen/qwen2.5-coder-32b-instruct"),
                      "key": cf_tok})
    return provs


def build_judge() -> Optional[Dict[str, Any]]:
    gem = os.environ.get("GEMINI_KEY") or os.environ.get("GEMINI_API_KEY")
    if gem:
        return {"name": "gemini", "kind": "gemini",
                "model": os.environ.get("GEMINI_MODEL", "gemini-2.0-flash"),
                "key": gem}
    return None


def chat(prov: Dict[str, Any], messages: List[Dict[str, str]],
         max_tokens: Optional[int] = None, temperature: Optional[float] = None) -> str:
    mt = max_tokens or MAX_TOKENS
    tp = TEMPERATURE if temperature is None else temperature
    kind = prov["kind"]
    if kind == "openai":
        headers = {"Authorization": f"Bearer {prov['key']}", "Content-Type": "application/json"}
        payload = {"model": prov["model"], "messages": messages,
                   "max_tokens": mt, "temperature": tp}
        data = _http_post(prov["url"], headers, payload)
        choices = data.get("choices") or []
        if not choices:
            return ""
        return (choices[0].get("message", {}).get("content") or "")
    if kind == "cf":
        headers = {"Authorization": f"Bearer {prov['key']}", "Content-Type": "application/json"}
        payload = {"messages": messages, "max_tokens": mt, "temperature": tp}
        data = _http_post(prov["url"] + prov["model"], headers, payload)
        res = data.get("result", {}) or {}
        return res.get("response") or res.get("text") or ""
    if kind == "gemini":
        url = (f"https://generativelanguage.googleapis.com/v1beta/models/"
               f"{prov['model']}:generateContent?key={prov['key']}")
        parts = [{"text": f"{m['role'].upper()}: {m['content']}"} for m in messages]
        payload = {"contents": [{"parts": parts}],
                   "generationConfig": {"maxOutputTokens": mt, "temperature": tp}}
        data = _http_post(url, {"Content-Type": "application/json"}, payload)
        cands = data.get("candidates") or [{}]
        content = cands[0].get("content", {}) or {}
        return "".join(p.get("text", "") for p in content.get("parts", []))
    raise RuntimeError(f"unknown provider kind: {kind}")


def chat_safe(prov: Dict[str, Any], messages: List[Dict[str, str]], **kw) -> Optional[str]:
    try:
        return retry(chat, prov, messages, what=f"chat:{prov['name']}", **kw)
    except Exception as exc:
        log_error(f"chat:{prov['name']}", exc)
        return None


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------
_BOX = re.compile(r"\\boxed\{([^{}]*)\}")
_CODE = re.compile(r"```(?:python|py)?\s*\n(.*?)```", re.DOTALL)


def extract_answer(text: str) -> Optional[str]:
    if not text:
        return None
    m = _BOX.findall(text)
    if m:
        return m[-1].strip()
    if "####" in text:
        tail = text.split("####")[-1].strip()
        return tail.splitlines()[0].strip() if tail else None
    return None


def norm_ans(s: Optional[str]) -> Optional[str]:
    if s is None:
        return None
    s = s.strip().lower().rstrip(".")
    s = re.sub(r"[\s,$]", "", s)
    return s


def extract_code(text: str) -> Optional[str]:
    if not text:
        return None
    m = _CODE.search(text)
    return m.group(1) if m else None


def run_code_tests(solution_code: Optional[str], tests: Optional[str]) -> Optional[bool]:
    if not CODE_EXEC or not solution_code or not tests:
        return None
    if not isinstance(tests, str):
        tests = json.dumps(tests)
    script = solution_code + "\n\n" + tests + "\n"
    path = None
    try:
        with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False, encoding="utf-8") as tf:
            tf.write(script)
            path = tf.name
        p = subprocess.run([sys.executable, path], capture_output=True,
                           timeout=CODE_TIMEOUT, text=True)
        return p.returncode == 0
    except Exception:
        return False
    finally:
        if path:
            try:
                os.remove(path)
            except Exception:
                pass


def judge_score(judge: Optional[Dict[str, Any]], problem: str, solution: str) -> Optional[float]:
    if not judge:
        return None
    prompt = ("You are a strict grader. Score the SOLUTION for the PROBLEM from 0 to 10 "
              "for correctness and quality. Reply with ONLY a number.\n\n"
              f"PROBLEM:\n{problem}\n\nSOLUTION:\n{solution}\n\nScore (0-10):")
    out = chat_safe(judge, [{"role": "user", "content": prompt}], max_tokens=8, temperature=0)
    if not out:
        return None
    m = re.search(r"(\d+(?:\.\d+)?)", out)
    return float(m.group(1)) if m else None


def solve(prov: Dict[str, Any], problem: str, domain: str) -> Tuple[Optional[str], int]:
    if domain == "code":
        sysmsg = ("You are an expert programmer. Return ONLY one Python code block "
                  "that solves the problem. No prose outside the code block.")
    elif domain == "math":
        sysmsg = ("You are an expert mathematician. Reason briefly, then give the "
                  "final answer inside \\boxed{}.")
    else:
        sysmsg = "You are a careful expert. Answer correctly and concisely."
    t0 = time.time()
    out = chat_safe(prov, [{"role": "system", "content": sysmsg},
                           {"role": "user", "content": problem}])
    ms = int((time.time() - t0) * 1000)
    return out, ms


# ---------------------------------------------------------------------------
# Problem iterator (reads the oracle dataset jsonl shards)
# ---------------------------------------------------------------------------
def iter_problems() -> Iterable[Tuple[str, Dict[str, Any]]]:
    from huggingface_hub import hf_hub_download
    try:
        files = retry(hf_api().list_repo_files, repo_id=SRC_REPO,
                      repo_type="dataset", what="list:src")
    except Exception as exc:
        log_error("list:src", exc)
        return
    shards = sorted(f for f in files if f.endswith(".jsonl"))
    log.info("[src] %s: %d jsonl shards", SRC_REPO, len(shards))
    for fn in shards:
        try:
            local = retry(hf_hub_download, repo_id=SRC_REPO, repo_type="dataset",
                          filename=fn, token=HF_TOKEN, local_dir=DL_DIR, what=f"dl:{fn}")
        except Exception as exc:
            log_error(f"dl:{fn}", exc)
            continue
        try:
            with open(local, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        yield fn, json.loads(line)
                    except Exception:
                        continue
        finally:
            try:
                os.remove(local)
            except Exception:
                pass


# ---------------------------------------------------------------------------
# Shard writer
# ---------------------------------------------------------------------------
class ShardWriter:
    def __init__(self, state: Dict[str, Any], seen: set):
        self.state = state
        self.seen = seen
        self.buffers: Dict[str, List[str]] = {s: [] for s in SPLITS}
        self.dupes = 0

    def add(self, rec: Dict[str, Any], method: str, domain: str,
            provider: str, ms: Optional[int]) -> bool:
        split = rec.pop("split")
        rid = sha_id(split, json.dumps(rec, ensure_ascii=False, sort_keys=True))
        if rid in self.seen:
            self.dupes += 1
            return False
        self.seen.add(rid)
        out = {"id": rid, "kind": split, "domain": domain, "method": method,
               "provider": provider, "solve_ms": ms, "self_generated": True,
               "verified": method.startswith("verified"), **rec}
        self.buffers[split].append(json.dumps(out, ensure_ascii=False))
        if len(self.buffers[split]) >= SHARD_ROWS:
            self.flush(split)
        return True

    def flush(self, split: str) -> None:
        buf = self.buffers[split]
        if not buf:
            return
        idx = self.state["shard_index"][split]
        fname = f"{split}-{idx:05d}.jsonl"
        local = os.path.join(DATA_DIR, split, fname)
        atomic_write_text(local, "\n".join(buf) + "\n")
        self.state["shard_index"][split] = idx + 1
        self.state["rows_out"][split] = self.state["rows_out"].get(split, 0) + len(buf)
        self.state["total_out"] = self.state.get("total_out", 0) + len(buf)
        self.buffers[split] = []
        save_state(self.state)
        save_seen(self.seen)
        commit_all()  # throttled -> avoids 429
        log.info("[flush] %s shard %d (+%d) | total=%d", split, idx, len(buf), self.state["total_out"])

    def flush_all(self) -> None:
        for s in SPLITS:
            self.flush(s)


# ---------------------------------------------------------------------------
# The council
# ---------------------------------------------------------------------------
def council_solve(row: Dict[str, Any], providers: List[Dict[str, Any]],
                  judge: Optional[Dict[str, Any]], writer: ShardWriter) -> str:
    problem = row.get("problem")
    if not problem or len(problem) < 8:
        return "skip"
    domain = row.get("domain") or "other"
    ans = row.get("answer")
    tests = row.get("tests")
    judge_only = bool(row.get("judge_only"))

    pool = random.sample(providers, min(N_SOLVERS, len(providers)))
    candidates: List[Dict[str, Any]] = []
    for prov in pool:
        text, ms = solve(prov, problem, domain)
        if not text:
            continue
        passed = None
        if domain == "code" and tests:
            code = extract_code(text) or text
            passed = run_code_tests(code, tests)
        elif ans:
            cand_ans = extract_answer(text)
            if cand_ans is not None:
                passed = (norm_ans(cand_ans) == norm_ans(ans))
        candidates.append({"prov": prov["name"], "text": text, "ms": ms,
                           "passed": passed, "score": None})

    if not candidates:
        return "none"

    passing = [c for c in candidates if c["passed"] is True]
    failing = [c for c in candidates if c["passed"] is False]

    best = None
    method = None
    scored: List[Dict[str, Any]] = []
    if passing:
        # EFFICIENCY selector: shortest passing solution, tie -> fastest
        best = sorted(passing, key=lambda c: (len(c["text"]), c["ms"]))[0]
        method = "verified"
    elif judge_only or (not ans and not tests):
        for c in candidates:
            s = judge_score(judge, problem, c["text"])
            if s is not None:
                c["score"] = s
                scored.append(c)
        if scored:
            top = max(scored, key=lambda c: c["score"])
            if top["score"] >= JUDGE_MIN:
                best = top
                method = f"judge:{top['score']:.1f}"
    if best is None:
        return "reject"

    sol = best["text"].strip()
    writer.add({"split": "sft", "prompt": problem, "response": sol},
               method, domain, best["prov"], best.get("ms"))

    # DPO pair when we have a clear loser (verified winner vs failing, or judge gap)
    loser = None
    if failing:
        loser = failing[0]
    elif scored and len(scored) > 1:
        lo = min(scored, key=lambda c: c["score"])
        if lo is not best and (best["score"] or 0) - (lo["score"] or 0) >= 2:
            loser = lo
    if loser:
        writer.add({"split": "dpo", "prompt": problem,
                    "chosen": sol, "rejected": loser["text"].strip()},
                   method + "|dpo", domain, best["prov"], best.get("ms"))
    return "kept"


def write_readme(state: Dict[str, Any]) -> None:
    rows = state.get("rows_out", {})
    md = [
        "---", "license: other", "tags: [damru, council, self-play, rlvr, sft, dpo]", "---", "",
        "# Damru Council (self-generated, verified)", "",
        "Auto-built by `damru_council.py` (Step 4). Problems come from the Oracle;",
        "solutions are generated by a free-provider council and VERIFIED (tests /",
        "answer match) or JUDGE-scored. No closed-model style is copied.", "",
        "## Splits", "",
        f"- **sft**: {rows.get('sft', 0)} -- {{prompt, response}} (verified/judged)",
        f"- **dpo**: {rows.get('dpo', 0)} -- {{prompt, chosen, rejected}}",
        "", f"**Total kept:** {state.get('total_out', 0)}", "",
        "Rows carry id, domain, method, provider, solve_ms, self_generated, verified.",
    ]
    atomic_write_text(README_PATH, "\n".join(md) + "\n")


def main() -> int:
    if not HF_TOKEN:
        log.error("HF_TOKEN env var is required.")
        return 2
    providers = build_providers()
    judge = build_judge()
    if not providers:
        log.error("No solver providers configured. Set at least one of: "
                  "NVIDIA_NIM_KEY, GROQ_API_KEY, MISTRAL_API_KEY, GH_MODELS_TOKEN, "
                  "or CF_ACCOUNT_ID + CF_API_TOKEN.")
        return 3
    log.info("=== Damru Council (Step 4) | out=%s | src=%s | solvers=%s | judge=%s ===",
             OUT_REPO, SRC_REPO, [p["name"] for p in providers],
             judge["name"] if judge else None)
    ensure_repo()
    restore_from_hf()
    state = load_state()
    state.setdefault("shard_index", {s: 0 for s in SPLITS})
    state.setdefault("rows_out", {s: 0 for s in SPLITS})
    for s in SPLITS:
        state["shard_index"].setdefault(s, 0)
        state["rows_out"].setdefault(s, 0)
    state.setdefault("total_out", 0)
    seen = load_seen()
    writer = ShardWriter(state, seen)
    deadline = time.time() + TIME_BUDGET_MIN * 60

    processed = set(state.get("problems_done", []))
    n_seen = state.get("problems_seen", 0)
    n_kept = 0
    stopped = False
    for fn, row in iter_problems():
        pid = row.get("id") or sha_id(row.get("problem", ""))
        if pid in processed:
            continue
        n_seen += 1
        try:
            res = council_solve(row, providers, judge, writer)
            if res == "kept":
                n_kept += 1
        except Exception as exc:
            log_error(f"council:{pid}", exc)
        processed.add(pid)
        if n_seen % 25 == 0:
            state["problems_done"] = list(processed)
            state["problems_seen"] = n_seen
            save_state(state)
            if time.time() > deadline:
                stopped = True
                break
            if n_seen % 100 == 0:
                log.info("[progress] seen=%d kept=%d dupes=%d", n_seen, n_kept, writer.dupes)
        if MAX_PROBLEMS and n_seen >= MAX_PROBLEMS:
            break

    writer.flush_all()
    state["problems_done"] = list(processed)
    state["problems_seen"] = n_seen
    write_readme(state)
    save_state(state)
    commit_all(force=True)
    log.info("=== %s. seen=%d kept=%d | splits=%s ===",
             "PARTIAL (re-run to continue)" if stopped else "DONE",
             n_seen, n_kept, state.get("rows_out", {}))
    log.info("Dataset: https://huggingface.co/datasets/%s", OUT_REPO)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        log.warning("Interrupted -- state saved, safe to re-run to resume.")
        sys.exit(130)
