/* DAMRU 2000 MODEL VAULT — 1000 aircraft + 1000 general executable parametric presets */
(function(){'use strict';if(window.DamruModelVault)return;
var AC_GROUPS={
 fighter:['F-35A Lightning II','F-35B Lightning II','F-35C Lightning II','F-22 Raptor','F-15EX Eagle II','F-16V Viper','F/A-18E Super Hornet','Rafale F4','Eurofighter Typhoon','Gripen E','Su-57 Felon','Su-75 Checkmate concept','J-20 Mighty Dragon','J-35A','KF-21 Boramae','KAAN','AMCA concept','Tejas Mk2','F-47 NGAD concept','GCAP concept','FCAS NGF concept','F/A-XX concept','Mitsubishi F-X concept','J-10C','J-16','Su-35S','MiG-35','FA-50 Fighting Eagle','T-7A Red Hawk','M-346 Master','Hongdu L-15','Yak-130','Hurjet','AERALIS concept','Mirage 2000-5'],
 bomber:['B-21 Raider','B-2 Spirit','B-1B Lancer','B-52J Stratofortress','Tu-160M2 Blackjack','Tu-22M3 Backfire','H-6K','PAK DA concept'],
 transport:['C-17 Globemaster III','C-130J Super Hercules','Airbus A400M Atlas','Kawasaki C-2','Y-20 Kunpeng','Il-76MD-90A','Embraer C-390 Millennium','KC-46A Pegasus','A330 MRTT','KC-130J','E-7 Wedgetail','E-2D Advanced Hawkeye','P-8A Poseidon','Saab GlobalEye','E-130J future command aircraft'],
 airliner:['Airbus A220-300','Airbus A319neo','Airbus A320neo','Airbus A321XLR','Airbus A330-900neo','Airbus A350-900','Airbus A350-1000','Airbus A380-800','Boeing 737 MAX 8','Boeing 737 MAX 10','Boeing 787-8','Boeing 787-9','Boeing 787-10','Boeing 777-8','Boeing 777-9','COMAC C919','COMAC C929 concept','MC-21-310','Embraer E190-E2','Embraer E195-E2','ATR 72-600','CRJ1000'],
 rotor:['Bell V-280 Valor','V-22 Osprey','Sikorsky-Boeing SB-1','AH-64E Apache','CH-47F Chinook','UH-60M Black Hawk','Airbus H160M Guepard','Leonardo AW149','Ka-52M','Mi-28NM'],
 drone:['MQ-25 Stingray','MQ-9B SkyGuardian','RQ-4 Global Hawk','RQ-170 Sentinel','Bayraktar Kizilelma','Bayraktar Akinci','GJ-11 Sharp Sword','S-70 Okhotnik-B','XQ-58A Valkyrie','YFQ-42A CCA']
};
var AC_VARIANTS=['Reference','Clean configuration','Long-range','High-payload','Low-observable','Maritime','Desert','Arctic','Trainer/display','Experimental'];
var GENERAL=['office-chair','dining-table','sofa','bed','cabinet','bookshelf','work-desk','floor-lamp','door','window','city-car','pickup-truck','motorcycle','bicycle','city-bus','train-coach','motor-boat','forklift','tractor','excavator','claw-hammer','combination-wrench','screwdriver','power-drill','circular-saw','pliers','toolbox','bench-vise','gear-pump','electric-motor','smartphone','laptop','monitor','keyboard','camera','speaker','wifi-router','3d-printer','quadcopter','service-robot','modern-house','office-building','bridge','communications-tower','warehouse','factory-cell','hospital-bed','microscope','telescope','wind-turbine'];
var GEN_VARIANTS=['Compact','Standard','Professional','Heavy-duty','Mini','XL','Outdoor','Industrial','Medical-grade style','Smart','Foldable','Modular','Vintage','Modern','Low-poly','Detailed','Mobile','Wall-mount','Desktop','Custom'];
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'')}
function hash(s){var h=2166136261;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){return function(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}}
function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
var aircraft=[],general=[],familyIndex=0;
Object.keys(AC_GROUPS).forEach(function(type){AC_GROUPS[type].forEach(function(name){familyIndex++;for(var v=0;v<10;v++){var id='AC-'+String(familyIndex).padStart(3,'0')+'-'+String(v+1).padStart(2,'0'),first=name.split(' ')[0],baseAlias=norm(first).replace(/(\d)[a-z]$/,'$1');aircraft.push({id:id,name:name+' · '+AC_VARIANTS[v],family:name,type:type,variant:AC_VARIANTS[v],variantIndex:v,kind:'aircraft',aliases:[norm(name),norm(first),baseAlias,slug(name)]});}})});
GENERAL.forEach(function(name,i){for(var v=0;v<20;v++){general.push({id:'GM-'+String(i+1).padStart(3,'0')+'-'+String(v+1).padStart(2,'0'),name:name.replace(/-/g,' ')+' · '+GEN_VARIANTS[v],family:name,type:generalType(i),variant:GEN_VARIANTS[v],variantIndex:v,kind:'general',aliases:[norm(name),slug(name)]});}});
var catalog=aircraft.concat(general),byId={};catalog.forEach(function(x){byId[x.id]=x});
function generalType(i){return i<10?'furniture':i<20?'vehicle':i<30?'tool-machine':i<40?'electronics-robot':i<47?'architecture':i<49?'medical-science':'energy'}
function choose(prompt){var m=String(prompt||'').match(/\[vault:([^\]]+)\]/i);if(m&&byId[m[1].toUpperCase()])return byId[m[1].toUpperCase()];var p=norm(prompt);if(!p)return null;var best=null,score=0;aircraft.forEach(function(e){e.aliases.forEach(function(a){if(a.length>=3&&p.indexOf(a)>=0&&a.length>score){best=e;score=a.length}})});if(best)return best;general.forEach(function(e){var a=norm(e.family);if(a.length>=4&&(p.indexOf(a)>=0||a.indexOf(p)>=0)&&a.length>score){best=e;score=a.length}});return best}
function mat(color,metal,rough,emit){var m={color:color,metalness:metal==null?.35:metal,roughness:rough==null?.42:rough};if(emit)m.emissive=emit;return m}
function aircraftSpec(e){var R=rng(hash(e.id)),O=[],type=e.type,scale=.9+R()*.24+(e.variantIndex===4?-.06:e.variantIndex===3?.12:0),base={fighter:[16,11,4],bomber:[34,38,5],transport:[43,42,8],airliner:[48,45,6],rotor:[17,15,5],drone:[11,16,2.4]}[type],L=base[0]*scale,W=base[1]*scale,H=base[2]*scale;var skin=mat(e.variantIndex===5?'#597386':e.variantIndex===6?'#ad8a55':e.variantIndex===7?'#dce5e9':type==='airliner'?'#e5e9ed':'#657381',.62,.3),dark=mat('#18212b',.55,.3),glass=mat('#17415a',.4,.14,'#062b40'),accent=mat(['#d95f45','#e2ad4c','#55b4d9','#6dbf78'][e.variantIndex%4],.35,.35),rubber=mat('#111318',.12,.9),metal=mat('#aeb8c4',.82,.2),hot=mat('#ff7635',.12,.28,'#a51d00');
 function add(id,t,size,pos,ma,rot,extra){var x={id:id,name:id,type:t,size:size||{},position:pos||[0,0,0],rotation:rot||[0,0,0],material:ma||skin};if(extra)for(var k in extra)x[k]=extra[k];O.push(x);return x}function box(id,w,h,d,p,ma,r){return add(id,'box',{w:w,h:h,d:d},p,ma,r)}function cyl(id,r,h,p,ma,rot){return add(id,'cylinder',{r:r,h:h},p,ma,rot)}
 if(type==='rotor'){
  add('fuselage','capsule',{r:H*.34,h:L*.35},[0,H*.62,0],skin,[90,0,0]);add('cockpit','sphere',{r:H*.29},[0,H*.7,L*.23],glass);box('tail-boom',H*.36,H*.34,L*.55,[0,H*.73,-L*.31],skin);add('tail-fin','wedge',{w:H*.85,h:H*.9,d:.15},[0,H*1.2,-L*.58],accent,[0,90,0]);cyl('main-rotor-hub',H*.1,H*.35,[0,H*1.08,0],metal);for(var i=0;i<4;i++)box('main-rotor-blade-'+(i+1),W*.48,.07,.22,[Math.cos(i*Math.PI/2)*W*.24,H*1.28,Math.sin(i*Math.PI/2)*W*.24],dark,[0,-i*90,0]);for(var j=0;j<4;j++)box('tail-rotor-'+(j+1),H*.72,.05,.12,[.08,H*1.05,-L*.6],dark,[j*45,0,0]);[-1,1].forEach(function(s){box('skid-'+s,.12,.12,L*.33,[s*H*.42,.12,0],metal);box('skid-brace-'+s,.1,H*.5,.1,[s*H*.35,H*.28,0],metal,[0,0,s*18])});
 } else {
  add('primary-fuselage','capsule',{r:H*.22,h:L*.68},[0,H*.55,0],skin,[90,0,0]);add('nose-radome','cone',{r:H*.22,h:L*.2},[0,H*.55,L*.44],skin,[90,0,0]);box('aft-fuselage',H*.44,H*.43,L*.18,[0,H*.55,-L*.42],skin);if(type!=='drone')add('cockpit-canopy','capsule',{r:H*.16,h:L*.08},[0,H*.8,L*.18],glass,[90,0,0]);
  var chord=L*(type==='airliner'?.17:type==='transport'?.22:.29),th=.1+H*.025;add('left-wing','wedge',{w:W*.5,h:chord,d:th},[-W*.25,H*.55,0],skin,[90,0,180]);add('right-wing','wedge',{w:W*.5,h:chord,d:th},[W*.25,H*.55,0],skin,[90,0,0]);box('left-leading-edge',W*.47,.08,.16,[-W*.27,H*.57,chord*.28],metal,[0,-10,0]);box('right-leading-edge',W*.47,.08,.16,[W*.27,H*.57,chord*.28],metal,[0,10,0]);
  add('tailplane-left','wedge',{w:W*.19,h:L*.11,d:th},[-W*.1,H*.67,-L*.37],skin,[90,0,180]);add('tailplane-right','wedge',{w:W*.19,h:L*.11,d:th},[W*.1,H*.67,-L*.37],skin,[90,0,0]);var fins=(type==='fighter'||type==='bomber'||type==='drone')?2:1;for(var f=0;f<fins;f++)add('vertical-tail-'+(f+1),'wedge',{w:L*.12,h:H*.55,d:.12},[(f-(fins-1)/2)*H*.38,H*.9,-L*.4],accent,[0,90,f?12:-12]);
  var engines=type==='bomber'?4:(type==='transport'&&R()>.45?4:2);if(type==='fighter'||type==='drone')engines=R()>.55?2:1;for(var n=0;n<engines;n++){var side=(n-(engines-1)/2),ex=engines===1?0:side*W/(engines+1),ez=type==='fighter'?-L*.25:L*.02;cyl('engine-nacelle-'+(n+1),H*.14,L*.17,[ex,H*.34,ez],dark,[90,0,0]);add('engine-intake-'+(n+1),'torus',{r:H*.14,tube:H*.025},[ex,H*.34,ez+L*.085],metal);add('engine-nozzle-'+(n+1),'torus',{r:H*.12,tube:H*.025},[ex,H*.34,ez-L*.085],hot);}
  if(type==='airliner'||type==='transport'){for(var w=0;w<16;w++){var z=L*.28-w*L*.035;[-1,1].forEach(function(s){add('cabin-window-'+s+'-'+w,'sphere',{r:H*.025},[s*H*.225,H*.67,z],glass)});}}
  [-1,1].forEach(function(s){box('intake-'+s,H*.18,H*.16,L*.12,[s*H*.27,H*.48,L*.08],dark,[0,s*8,0]);add('navigation-light-'+s,'sphere',{r:.08+H*.01},[s*W*.48,H*.58,0],s<0?mat('#ff334d',.1,.2,'#ff0028'):mat('#49ff88',.1,.2,'#00cc4d'));});
  [[-W*.16,-L*.18],[W*.16,-L*.18],[0,L*.22]].forEach(function(p,i){box('landing-strut-'+(i+1),.08,H*.38,.08,[p[0],H*.21,p[1]],metal);add('landing-wheel-'+(i+1),'torus',{r:H*.075,tube:H*.028},[p[0],.08,p[1]],rubber,[0,90,0]);});
  if(type==='fighter'||type==='drone'){[-1,1].forEach(function(s){for(var k=0;k<2;k++)add('pylon-'+s+'-'+k,'capsule',{r:.08,h:L*.18},[s*W*(.22+k*.1),H*.34,-L*.02],dark,[90,0,0]);});box('internal-bay',H*.5,.07,L*.24,[0,H*.31,-L*.02],dark);}
 }
 return{name:'VAULT '+e.family+' '+e.variant,units:'m',background:'#050914',environment:{ground:true,grid:true},camera:{position:[W*.9,H*1.45,L*.9],target:[0,H*.55,0]},metadata:{generator:'Damru Aircraft Vault',vaultId:e.id,family:e.family,configuration:e.variant,profile:type,parametricReference:true,identityMatched:true,notOEMCAD:true},simulation:{domain:'aerospace',massModel:'estimated',environment:'earth/space selectable'},objects:O};
}
function generalSpec(e){var R=rng(hash(e.id)),O=[],i=GENERAL.indexOf(e.family),type=e.type,s=.72+R()*.72,color=['#d8734f','#5d82ac','#55a979','#d3a84f','#9b72bd'][e.variantIndex%5],body=mat(color,.28,.46),dark=mat('#252b35',.4,.55),metal=mat('#aab4c1',.75,.23),glass=mat('#3181a6',.3,.16,'#06283a');function add(id,t,size,p,m,r,extra){var x={id:id,name:id,type:t,size:size||{},position:p||[0,0,0],rotation:r||[0,0,0],material:m||body};if(extra)for(var k in extra)x[k]=extra[k];O.push(x)}function box(id,w,h,d,p,m,r){add(id,'box',{w:w,h:h,d:d},p,m,r)}
 if(type==='furniture'){box('main-surface',5*s,.35,3*s,[0,2.8*s,0],body);for(var n=0;n<4;n++){var x=(n%2?1:-1)*2*s,z=(n>1?1:-1)*1.1*s;box('support-'+(n+1),.28,2.8*s,.28,[x,1.4*s,z],dark)}if(/chair|sofa|bed/.test(e.family)){box('backrest',5*s,2.8*s,.3,[0,4*s,1.35*s],body);for(var q=0;q<4;q++)add('cushion-'+q,'box',{w:1.05*s,h:.35,d:1.8*s},[(q-1.5)*1.1*s,3.1*s,0],mat(q%2?'#e0ad58':color,.1,.7));}for(var a=0;a<6;a++)add('detail-'+a,'cylinder',{r:.12*s,h:.5*s},[(a-2.5)*.55*s,3.25*s,0],metal);}
 else if(type==='vehicle'){box('chassis',4*s,.5,7*s,[0,.8*s,0],dark);box('body-shell',3.7*s,1.5*s,5.4*s,[0,1.7*s,0],body);box('cabin',3.15*s,1.25*s,2.5*s,[0,2.8*s,-.25*s],glass);for(var w=0;w<4;w++){var sx=w%2?1:-1,sz=w>1?1:-1;add('wheel-'+w,'torus',{r:.68*s,tube:.24*s},[sx*2*s,.75*s,sz*2.2*s],dark,[0,90,0]);add('hub-'+w,'cylinder',{r:.28*s,h:.2*s},[sx*2*s,.75*s,sz*2.2*s],metal,[0,0,90]);}box('front-module',3.7*s,.5,.5*s,[0,1.15*s,3*s],metal);box('rear-module',3.7*s,.5,.5*s,[0,1.15*s,-3*s],metal);}
 else if(type==='tool-machine'){add('main-handle','capsule',{r:.38*s,h:4*s},[0,2.2*s,0],dark);box('working-head',3*s,1*s,1*s,[0,4.5*s,0],body);for(var t=0;t<8;t++)add('mechanism-'+t,t%2?'cylinder':'box',t%2?{r:.25*s,h:.7*s}:{w:.5*s,h:.5*s,d:.7*s},[(t-3.5)*.42*s,4.5*s,0],t%2?metal:body,[0,0,90]);add('interface-ring','torus',{r:.55*s,tube:.1*s},[0,.35*s,0],metal,[90,0,0]);}
 else if(type==='electronics-robot'){box('chassis',5*s,3.2*s,.65*s,[0,2*s,0],dark);box('display',4.4*s,2.5*s,.12*s,[0,2.2*s,.4*s],glass);for(var b=0;b<12;b++)add('control-'+b,'box',{w:.42*s,h:.24*s,d:.12*s},[((b%6)-2.5)*.65*s,(Math.floor(b/6)-.5)*.55*s+1.3*s,.55*s],b%3?body:metal);[-1,1].forEach(function(x){add('side-module-'+x,'cylinder',{r:.45*s,h:1.4*s},[x*3*s,2*s,0],body);});box('base',5.8*s,.35,2*s,[0,.2*s,0],metal);}
 else if(type==='architecture'){box('foundation',10*s,.5,8*s,[0,.25,0],dark);var floors=4+e.variantIndex%5;for(var f=0;f<floors;f++){box('floor-'+f,8*s,.35,6*s,[0,.7+f*2.2*s,0],body);for(var c=0;c<4;c++){var x=c%2?1:-1,z=c>1?1:-1;box('column-'+f+'-'+c,.35,2.2*s,.35,[x*3.4*s,1.8*s+f*2.2*s,z*2.4*s],metal);}for(var w=0;w<6;w++)box('window-'+f+'-'+w,.7*s,.85*s,.1,[(w-2.5)*1.1*s,1.9*s+f*2.2*s,3.02*s],glass);}box('roof',9*s,.4,7*s,[0,.9+floors*2.2*s,0],dark);}
 else {box('instrument-base',6*s,.4,4*s,[0,.2,0],dark);box('vertical-stand',.55,5*s,.55,[-1.8*s,2.6*s,0],metal);add('optical-body','cylinder',{r:1.15*s,h:4.2*s},[.6*s,3.5*s,0],body,[90,0,0]);for(var l=0;l<5;l++)add('lens-'+l,'torus',{r:(1.18-l*.08)*s,tube:.08*s},[.6*s,3.5*s,(l-2)*.72*s],l%2?glass:metal);add('sensor','sphere',{r:.65*s},[.6*s,3.5*s,2.4*s],glass);}
 return{name:'VAULT '+e.name,units:'m',background:'#060a12',environment:{ground:true,grid:true},metadata:{generator:'Damru General Model Vault',vaultId:e.id,family:e.family,configuration:e.variant,category:type,parametricPreset:true},simulation:{domain:type==='medical-science'?'science':'general',materialModel:'editable'},objects:O};}
function build(prompt){var e=typeof prompt==='object'?prompt:choose(prompt);if(!e)return null;return e.kind==='aircraft'?aircraftSpec(e):generalSpec(e)}
function css(){if(document.getElementById('dmv-css'))return;var s=document.createElement('style');s.id='dmv-css';s.textContent=`#dmv{position:fixed;inset:0;z-index:125000;background:rgba(2,4,9,.91);backdrop-filter:blur(13px);display:none;align-items:center;justify-content:center;padding:12px;color:#eef3ff;font-family:Inter,system-ui}#dmv.on{display:flex}.dmv-card{width:min(1050px,100%);height:min(830px,95dvh);display:flex;flex-direction:column;background:#0d1421;border:1px solid #33425e;border-radius:18px;overflow:hidden}.dmv-head{display:flex;align-items:center;gap:10px;padding:14px;border-bottom:1px solid #27334a}.dmv-head h2{margin:0;flex:1;font-size:18px}.dmv-head small{display:block;color:#8798b8;font-size:10px}.dmv-x,.dmv-btn{background:#1d2940;color:#fff;border:1px solid #3b4b6b;border-radius:9px;padding:8px 11px;cursor:pointer}.dmv-search{display:flex;gap:8px;padding:12px}.dmv-search input{flex:1;background:#09101c;color:#fff;border:1px solid #344461;border-radius:10px;padding:11px}.dmv-tabs{display:flex;gap:7px;padding:0 12px 10px;flex-wrap:wrap}.dmv-grid{flex:1;overflow:auto;display:grid;grid-template-columns:repeat(3,1fr);gap:8px;padding:10px 12px}.dmv-item{border:1px solid #283750;background:#121c2c;border-radius:11px;padding:10px;cursor:pointer}.dmv-item:hover{border-color:#557fdb}.dmv-item b{display:block;font-size:12px}.dmv-item span{font-size:9px;color:#8fa4ca}.dmv-item button{float:right;background:#315fca;color:white;border:0;border-radius:7px;padding:5px 7px}.dmv-foot{padding:9px 13px;border-top:1px solid #26334a;font-size:10px;color:#8ca0c3}@media(max-width:720px){.dmv-grid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
var filter='all',query='';function modal(){if(document.getElementById('dmv'))return;css();var m=document.createElement('div');m.id='dmv';m.innerHTML='<div class="dmv-card"><div class="dmv-head"><span style="font-size:26px">🗃️</span><h2>Damru 2000 Model Vault<small>1000 aircraft configurations · 1000 general parametric presets</small></h2><button class="dmv-x">×</button></div><div class="dmv-search"><input id="dmv-q" placeholder="Search F-35, B-21, A321XLR, robot, chair, microscope…"><button class="dmv-btn" id="dmv-random">Surprise</button></div><div class="dmv-tabs"><button class="dmv-btn" data-f="all">All 2000</button><button class="dmv-btn" data-f="aircraft">Aircraft 1000</button><button class="dmv-btn" data-f="general">General 1000</button></div><div class="dmv-grid" id="dmv-grid"></div><div class="dmv-foot">Executable parametric presets—not downloaded OEM meshes. Select a model; Damru builds an editable baseline then runs Deep Build with no-downgrade protection.</div></div>';document.body.appendChild(m);m.querySelector('.dmv-x').onclick=close;m.onclick=function(e){if(e.target===m)close()};document.getElementById('dmv-q').oninput=function(){query=this.value;render()};document.getElementById('dmv-random').onclick=function(){load(catalog[Math.floor(Math.random()*catalog.length)])};[].forEach.call(m.querySelectorAll('[data-f]'),function(b){b.onclick=function(){filter=this.dataset.f;render()}});render()}
function render(){var g=document.getElementById('dmv-grid');if(!g)return;var qn=norm(query),a=catalog.filter(function(e){return(filter==='all'||e.kind===filter)&&(!qn||norm(e.name+' '+e.id).indexOf(qn)>=0)}).slice(0,120);g.innerHTML=a.map(function(e){return'<div class="dmv-item" data-id="'+e.id+'"><button>Build</button><b>'+e.name+'</b><span>'+e.id+' · '+e.type+'</span></div>'}).join('')+(a.length?'<div style="grid-column:1/-1;color:#7588aa;font-size:10px">Showing first '+a.length+' matches. Search narrows all 2000 presets.</div>':'<div>No model found</div>');[].forEach.call(g.querySelectorAll('[data-id]'),function(x){x.onclick=function(){load(byId[this.dataset.id])}})}
function load(e){close();if(!window.DamruVisualise){alert('Visualise not loaded');return}window.DamruVisualise.open('[vault:'+e.id+'] '+e.family+' '+e.variant)}function open(){modal();document.getElementById('dmv').classList.add('on')}function close(){var m=document.getElementById('dmv');if(m)m.classList.remove('on')}
function inject(){var top=document.getElementById('dv-top');if(top&&!document.getElementById('dmv-launch')){var b=document.createElement('button');b.id='dmv-launch';b.className='dv-btn';b.textContent='🗃 2000 Vault';b.onclick=open;top.appendChild(b)}}
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});setTimeout(inject,1000);
window.DamruModelVault={open:open,close:close,choose:choose,build:build,aircraftSpec:aircraftSpec,generalSpec:generalSpec,catalog:catalog,aircraft:aircraft,general:general,byId:byId,stats:{aircraft:aircraft.length,general:general.length,total:catalog.length,families:familyIndex,archetypes:GENERAL.length}};
})();
