/* DAMRU SIMLAB v1.0 — browser-side manufacturing digital twin.
 * Analyses the live Visualise scene without network calls: bed fit, orientation,
 * ground contact, triangle/mesh complexity, slenderness and approximate volume.
 * Can auto-fit/centre/place the scene and export a signed manufacturing passport.
 * Honest scope: geometric/printability preflight, not structural FEA certification.
 */
(function(){
'use strict';
if(window.DamruSimLab)return;
var CFG={bedX:220,bedY:220,bedZ:250,margin:5};
function q(id){return document.getElementById(id)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
function injectCSS(){if(q('dsl-css'))return;var s=document.createElement('style');s.id='dsl-css';s.textContent=''
+'#dsl-modal{position:fixed;inset:0;z-index:100450;background:rgba(3,5,9,.9);display:none;align-items:center;justify-content:center;padding:12px;font-family:Inter,system-ui;color:#ecf1fa}#dsl-modal.on{display:flex}'
+'#dsl-card{width:min(820px,100%);max-height:94vh;overflow:auto;background:#0e131d;border:1px solid #303a50;border-radius:16px;padding:16px;box-shadow:0 25px 90px #000}.dsl-head{display:flex;gap:10px;align-items:center}.dsl-head h2{margin:0;flex:1;font-size:18px}'
+'.dsl-btn{background:#202a40;color:#fff;border:1px solid #3a4664;border-radius:9px;padding:9px 12px;cursor:pointer}.dsl-btn.primary{background:#e8623d;border-color:#e8623d}.dsl-btn.good{background:#176946;border-color:#299569}'
+'.dsl-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}.dsl-kpi{background:#151b27;border:1px solid #283249;border-radius:11px;padding:10px}.dsl-kpi b{display:block;font-size:18px}.dsl-kpi span{font-size:11px;color:#9ba6bd}'
+'#dsl-score{font-size:38px;font-weight:800}.dsl-bar{height:10px;background:#252d3f;border-radius:9px;overflow:hidden}.dsl-bar i{display:block;height:100%;background:linear-gradient(90deg,#e84c55,#ffbd55,#55d88a)}'
+'#dsl-findings{display:grid;gap:7px}.dsl-find{padding:9px 10px;border-radius:9px;background:#171d29;border-left:4px solid #6f7a91;font-size:13px}.dsl-find.bad{border-color:#ef6471}.dsl-find.warn{border-color:#ffbb55}.dsl-find.good{border-color:#56d692}'
+'.dsl-controls{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.dsl-in{width:68px;background:#151b27;color:white;border:1px solid #34405b;border-radius:7px;padding:8px}.dsl-note{font-size:11px;color:#8994aa;margin-top:10px}@media(max-width:650px){.dsl-grid{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
function modal(){if(q('dsl-modal'))return;injectCSS();var m=document.createElement('div');m.id='dsl-modal';m.innerHTML='<div id="dsl-card"><div class="dsl-head"><span style="font-size:26px">🧪</span><h2>Damru SimLab <small style="color:#8c97ac;font-weight:500">manufacturing digital twin</small></h2><button class="dsl-btn" id="dsl-x">×</button></div>'
+'<div style="display:flex;gap:14px;align-items:center;margin-top:12px"><div id="dsl-score">—</div><div style="flex:1"><div id="dsl-verdict">Build a model, then analyse.</div><div class="dsl-bar"><i id="dsl-scorebar" style="width:0%"></i></div></div></div>'
+'<div class="dsl-grid"><div class="dsl-kpi"><b id="dsl-size">—</b><span>model X × Y × Z mm</span></div><div class="dsl-kpi"><b id="dsl-meshes">—</b><span>printable meshes</span></div><div class="dsl-kpi"><b id="dsl-tris">—</b><span>triangles</span></div><div class="dsl-kpi"><b id="dsl-volume">—</b><span>bbox volume cm³</span></div></div>'
+'<div class="dsl-controls"><label>Bed X <input class="dsl-in" id="dsl-bx" type="number" value="220"></label><label>Y <input class="dsl-in" id="dsl-by" type="number" value="220"></label><label>Z <input class="dsl-in" id="dsl-bz" type="number" value="250"></label><label>Margin <input class="dsl-in" id="dsl-mg" type="number" value="5"></label></div>'
+'<h3 style="font-size:13px;color:#aeb8ce">Findings</h3><div id="dsl-findings"><div class="dsl-find">No analysis yet.</div></div>'
+'<div class="dsl-controls"><button class="dsl-btn primary" id="dsl-run">Analyse now</button><button class="dsl-btn good" id="dsl-fix">Auto-fit + place on bed</button><button class="dsl-btn" id="dsl-pass">Export manufacturing passport</button><button class="dsl-btn" id="dsl-print">Open Print Forge</button></div>'
+'<div class="dsl-note">SimLab performs deterministic geometry checks, not certified stress/thermal FEA. Physical printing always requires slicer preview and human supervision.</div></div>';document.body.appendChild(m);bind()}
function scene(){var d=window.DamruVisualise;if(!d||!d.state||!d.state.root)throw new Error('Open Visualise and build a model first');return d.state}
function transformPoint(x,y,z,e){return{x:e[0]*x+e[4]*y+e[8]*z+e[12],y:e[1]*x+e[5]*y+e[9]*z+e[13],z:e[2]*x+e[6]*y+e[10]*z+e[14]}}
function bounds(root){var mn={x:Infinity,y:Infinity,z:Infinity},mx={x:-Infinity,y:-Infinity,z:-Infinity},meshes=0,tris=0;root.updateMatrixWorld(true);root.traverse(function(o){if(!o.isMesh||!o.geometry)return;meshes++;var g=o.geometry;if(!g.boundingBox&&g.computeBoundingBox)g.computeBoundingBox();var b=g.boundingBox;if(!b)return;var xs=[b.min.x,b.max.x],ys=[b.min.y,b.max.y],zs=[b.min.z,b.max.z],e=o.matrixWorld.elements;xs.forEach(function(x){ys.forEach(function(y){zs.forEach(function(z){var p=transformPoint(x,y,z,e);mn.x=Math.min(mn.x,p.x);mn.y=Math.min(mn.y,p.y);mn.z=Math.min(mn.z,p.z);mx.x=Math.max(mx.x,p.x);mx.y=Math.max(mx.y,p.y);mx.z=Math.max(mx.z,p.z)})})});var pos=g.attributes&&g.attributes.position;tris+=g.index?g.index.count/3:(pos?pos.count/3:0)});if(!meshes)return null;return{min:mn,max:mx,size:{x:mx.x-mn.x,y:mx.y-mn.y,z:mx.z-mn.z},meshes:meshes,tris:Math.round(tris)}}
function n(v){return Math.round(v*10)/10}
function config(){CFG.bedX=+q('dsl-bx').value||220;CFG.bedY=+q('dsl-by').value||220;CFG.bedZ=+q('dsl-bz').value||250;CFG.margin=+q('dsl-mg').value||5;return CFG}
function analyse(){var st=scene(),b=bounds(st.root);if(!b)throw new Error('No printable meshes');var c=config(),f=[],score=100;var sx=b.size.x,depth=b.size.z,height=b.size.y;var usable={x:c.bedX-2*c.margin,y:c.bedY-2*c.margin,z:c.bedZ-c.margin};if(sx>usable.x||depth>usable.y||height>usable.z){f.push({level:'bad',text:'Model exceeds build volume after safety margin.'});score-=45}else f.push({level:'good',text:'Model fits configured printer bed.'});if(b.min.y<-0.01){f.push({level:'bad',text:'Geometry crosses below build plane by '+n(-b.min.y)+' mm.'});score-=20}else if(b.min.y>1){f.push({level:'warn',text:'Model floats '+n(b.min.y)+' mm above bed; supports/placement needed.'});score-=12}else f.push({level:'good',text:'Model touches build plane.'});var slender=height/Math.max(1,Math.min(sx,depth));if(slender>5){f.push({level:'warn',text:'Tall/slender ratio '+n(slender)+':1 may wobble; add brim or widen base.'});score-=15}if(b.tris>1000000){f.push({level:'warn',text:'Very dense mesh ('+b.tris.toLocaleString()+' triangles); slicing may be slow.'});score-=10}else f.push({level:'good',text:'Mesh complexity is manageable.'});if(b.meshes>500){f.push({level:'warn',text:'High part count ('+b.meshes+'); merge parts before production.'});score-=8}var volume=(sx*depth*height)/1000;score=Math.max(0,Math.min(100,score));var report={version:'damru-simlab-1',timestamp:new Date().toISOString(),design:(st.lastSpec&&st.lastSpec.name)||'untitled',units:'mm',score:score,verdict:score>=85?'READY FOR SLICER REVIEW':score>=60?'REPAIR RECOMMENDED':'BLOCKED UNTIL FIXED',bounds:b,printDimensions:{x:n(sx),y:n(depth),z:n(height)},bed:c,bboxVolumeCm3:n(volume),findings:f,research:st.research||[],disclaimer:'Geometric preflight only; not structural certification.'};render(report);window.__damruLastSimReport=report;return report}
function render(r){q('dsl-score').textContent=r.score;q('dsl-scorebar').style.width=r.score+'%';q('dsl-verdict').textContent=r.verdict;q('dsl-size').textContent=r.printDimensions.x+'×'+r.printDimensions.y+'×'+r.printDimensions.z;q('dsl-meshes').textContent=r.bounds.meshes;q('dsl-tris').textContent=r.bounds.tris.toLocaleString();q('dsl-volume').textContent=r.bboxVolumeCm3;q('dsl-findings').innerHTML=r.findings.map(function(x){return'<div class="dsl-find '+x.level+'">'+esc(x.text)+'</div>'}).join('')}
function autoFix(){var st=scene(),b=bounds(st.root),c=config();if(!b)return;var usableX=c.bedX-2*c.margin,usableD=c.bedY-2*c.margin,usableH=c.bedZ-c.margin;var scale=Math.min(1,usableX/Math.max(.001,b.size.x),usableD/Math.max(.001,b.size.z),usableH/Math.max(.001,b.size.y));st.root.scale.multiplyScalar(scale);st.root.updateMatrixWorld(true);b=bounds(st.root);st.root.position.x-=((b.min.x+b.max.x)/2);st.root.position.z-=((b.min.z+b.max.z)/2);st.root.position.y-=b.min.y;st.root.updateMatrixWorld(true);if(st.orbit){st.orbit.target.set(0,Math.max(1,b.size.y*scale/2),0);st.orbit.update()}analyse()}
function download(name,obj){var blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},2000)}
function passport(){var r=window.__damruLastSimReport||analyse();var raw=JSON.stringify(r),h=0;for(var i=0;i<raw.length;i++)h=((h<<5)-h+raw.charCodeAt(i))|0;r.localFingerprint=('00000000'+(h>>>0).toString(16)).slice(-8);download('damru-manufacturing-passport.json',r)}
function bind(){q('dsl-x').onclick=close;q('dsl-run').onclick=function(){try{analyse()}catch(e){alert(e.message)}};q('dsl-fix').onclick=function(){try{autoFix()}catch(e){alert(e.message)}};q('dsl-pass').onclick=function(){try{passport()}catch(e){alert(e.message)}};q('dsl-print').onclick=function(){if(window.DamruPrintForge)window.DamruPrintForge.open();else alert('Print Forge not loaded')};q('dsl-modal').onclick=function(e){if(e.target===this)close()}}
function open(){modal();q('dsl-modal').classList.add('on');try{analyse()}catch(e){}}
function close(){if(q('dsl-modal'))q('dsl-modal').classList.remove('on')}
function inject(){var top=q('dv-top');if(top&&!q('dsl-launch')){var b=document.createElement('button');b.id='dsl-launch';b.className='dv-btn';b.textContent='🧪 SimLab';b.onclick=open;var ref=q('dpf-launch')||null;top.insertBefore(b,ref)}}
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});setTimeout(inject,1200);
window.DamruSimLab={open:open,analyse:analyse,autoFix:autoFix,bounds:bounds};
})();
